<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../../resources/stylesheets/wasmsgxml.css"?>
<TMSSource name="TivoliMessages" tmsVersion="1.0" xml:lang="en">
<!-- CMVC MSG File Name = ws/code/sib.ra/src/com/ibm/ws/sib/ra/CWSIVMessages.nlsprops -->
<!-- DO NOT EDIT THIS FILE - This file was generated by the XML/Html & Property emitter -->
<!-- BEGIN MESSAGES -->
<Message ID="CWSIV0770W" severity="W" prefix="yes">
  <MsgText pgmKey="CONSUMER_FAILED_CWSIV0770" varFormat="Java">
    CONSUMER_FAILED_CWSIV0770=CWSIV0770W: A consumer for remote destination {0} on bus {1} for endpoint activation {2} failed with exception {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter received an exception for an existing consumer on a remote queue point.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine with a queue point for the given destination is available.  The resource adapter will automatically re-attempt to recreate the consumer periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV0160E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_XARESOURCE_CWSIV0160" varFormat="Java">
    INVALID_XARESOURCE_CWSIV0160=CWSIV0160E: An SIXAResource is not a valid transaction parameter.
  </MsgText>
  <Explanation>
    The use of an SIXAResource as the transaction parameter is not supported when using the RA_CONNECTION implementation of the Platform Messaging core SPI because global transactions are handled by the resource adapter.
  </Explanation>
  <UserResponse>
    If the application must handle global transactions explicitly then use a different implementation of the Platform Messaging core SPI, otherwise pass null as the transaction parameter.
  </UserResponse>
</Message>
<Message ID="CWSIV0777I" severity="I" prefix="yes">
  <MsgText pgmKey="CONNECTED_CWSIV0777" varFormat="Java">
    CONNECTED_CWSIV0777=CWSIV0777I: A connection to messaging engine {0} for destination {1} on bus {2} has been successfully created.
  </MsgText>
  <Explanation>
    The inbound resource adapter successfully created a connection to a messaging engine for the given endpoint activation.
  </Explanation>
  <UserResponse>
    No action is required.
  </UserResponse>
</Message>
<Message ID="CWSIV0555E" severity="E" prefix="yes">
  <MsgText pgmKey="MESSAGING_ENGINE_STARTING_CWSIV0555" varFormat="Java">
    MESSAGING_ENGINE_STARTING_CWSIV0555=CWSIV0555E: The exception {0} was thrown when processing the startup of messaging engine {1} on bus {2} for endpoint activation {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to process the given messaging engine when it received an exception.  Messages from destinations localized on that messaging engine will not be received by the message-driven bean. If the linked exception is an authentication exception then ensure that the activation specification has been associated with a valid authentication alias.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV1152E" severity="E" prefix="yes">
  <MsgText pgmKey="WAS_ENDPOINT_FACTORY_CWSIV1152" varFormat="Java">
    WAS_ENDPOINT_FACTORY_CWSIV1152=CWSIV1152E: An internal error occurred. The message endpoint factory {0} passed to the resource adapter did not implement the expected interface {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter requires the message endpoint factory to implement the given interface in order to obtain the unique name of the message-driven bean.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0901E" severity="E" prefix="yes">
  <MsgText pgmKey="SELECTION_FACTORY_CWSIV0901" varFormat="Java">
    SELECTION_FACTORY_CWSIV0901=CWSIV0901E: An internal error occurred. The exception {0} was thrown while attempting to obtain an instance of the SelectionCriteriaFactory.
  </MsgText>
  <Explanation>
    An exception was created during the attempt to obtain an instance of the SelectionCriteriaFactory.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0805E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_LISTENER_FAILED_CWSIV0805" varFormat="Java">
    CREATE_LISTENER_FAILED_CWSIV0805=CWSIV0805E: The exception {0} was thrown during the creation of a consumer for the new destination {1} on messaging engine {2} on bus {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a consumer for the given new destination when it received an exception.  Messages from that queue point will not be received by the message-driven bean.
  </Explanation>
  <UserResponse>
    See the linked exception for the cause.  After resolving the issue, restart the messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0803E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_LISTENER_FAILED_CWSIV0803" varFormat="Java">
    CREATE_LISTENER_FAILED_CWSIV0803=CWSIV0803E: The exception {0} was thrown during the creation of a consumer for the destination {1} on messaging engine {2} on bus {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a consumer for the given destination when it received an exception.  Messages from that destination localization will not be received by the message-driven bean.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0405E" severity="E" prefix="yes">
  <MsgText pgmKey="LOCAL_TRAN_BEGIN_CWSIV0405" varFormat="Java">
    LOCAL_TRAN_BEGIN_CWSIV0405=CWSIV0405E: An internal error occurred. The exception {0} was thrown while the container was attempting to begin a local transaction.
  </MsgText>
  <Explanation>
    An exception was created while the container was attempting to begin a local transaction.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0551W" severity="W" prefix="yes">
  <MsgText pgmKey="MAX_CONCURRENCY_CWSIV0551" varFormat="Java">
    MAX_CONCURRENCY_CWSIV0551=CWSIV0551W: The maximum concurrency for the MDB {0} was set to {1} in it&apos;&apos;s activation specification. This is higher than the JCA maximum pool size of {2} and so the MDB&apos;&apos;s maximum concurrency has been lowered to {3}
  </MsgText>
  <Explanation>
    The configuration of the maximum concurrency on the activation specification was set to high or the maximum concurrency on the JCA&apos;s maximum pool size was set too low. This should not cause a problem because Platform Messaging will lower the maximum concurrency on the activation specification but a warning is issued to the user to let the user know that the maximum concurrency they have configured will not be used.
  </Explanation>
  <UserResponse>
    This warning will continue to be shown whenever the message-driven bean is started. To remove this warning message lower the activation specifications maximum concurrency or raise the maximum pool size of the JCA&apos;s endpoint pool (using the JVM system property com.ibm.websphere.ejbcontainer.poolSize)
  </UserResponse>
</Message>
<Message ID="CWSIV0606E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_SESSION_CWSIV0606" varFormat="Java">
    INVALID_SESSION_CWSIV0606=CWSIV0606E: An internal error occurred. When attempting to delete the message handle {1} under transaction {2}, the session {0} was not of the required type {3}
  </MsgText>
  <Explanation>
    The resource adapter encountered a problem while attempting to delete a message handle
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0652E" severity="E" prefix="yes">
  <MsgText pgmKey="ME_NAME_REQUIRED_CWSIV0652" varFormat="Java">
    ME_NAME_REQUIRED_CWSIV0652=CWSIV0652E: A specific messaging engine must be specified to use JMS resources within a transaction. The connection property {0} must be set to {1}.
  </MsgText>
  <Explanation>
    To permit the recovery of transactions it is necessary that a connection factory target a specific messaging engine in the bus.
  </Explanation>
  <UserResponse>
    Change the connection factory properties &apos;targetGroup&apos; to &apos;the name of a messaging engine in the bus&apos;, &apos;targetType&apos; to &apos;ME&apos; and &apos;targetSignificance&apos; to &apos;Required&apos;.
  </UserResponse>
</Message>
<Message ID="CWSIV0452E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_ACTIVATION_SPEC_CWSIV0452" varFormat="Java">
    INVALID_ACTIVATION_SPEC_CWSIV0452=CWSIV0452E: The exception {1} was thrown while attempting to validate the activation specification {0} during endpoint activation.
  </MsgText>
  <Explanation>
    During the activation of an endpoint the given activation specification was determined to be incorrect.
  </Explanation>
  <UserResponse>
    See linked exception for incorrect properties and correct values in administered activation specification or message-driven bean&apos;s deployment descriptor.
  </UserResponse>
</Message>
<Message ID="CWSIV0200E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_SESSION_CWSIV0200" varFormat="Java">
    INVALID_SESSION_CWSIV0200=CWSIV0200E: The connection from which this session was created has been invalidated.
  </MsgText>
  <Explanation>
    A previous error has caused the connection to be no longer valid.
  </Explanation>
  <UserResponse>
    Check error logs to determine cause of previous error.  The application should create a new connection and session.
  </UserResponse>
</Message>
<Message ID="CWSIV1201E" severity="E" prefix="yes">
  <MsgText pgmKey="UNCOORD_TRAN_CWSIV1201" varFormat="Java">
    UNCOORD_TRAN_CWSIV1201=CWSIV1201E: An internal error occurred. The exception {1} was received when attempting to create an uncoordinated transaction on connection {0}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to create an uncoordinated transaction on the given connection.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0851E" severity="E" prefix="yes">
  <MsgText pgmKey="ON_MESSAGE_CWSIV0851" varFormat="Java">
    ON_MESSAGE_CWSIV0851=CWSIV0851E: An internal error occurred. The exception {0} was thrown while attempting to obtain an instance of the onMessage method.
  </MsgText>
  <Explanation>
    An exception was created during the attempt to obtain an instance of the onMessage method.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0515E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_USEDESTWILDCARD_CWSIV0515" varFormat="Java">
    INVALID_PROPERTY_USEDESTWILDCARD_CWSIV0515=CWSIV0515E: The &quot;use destination wildcard&quot; property was set on a Core SPI activation specification whilst using a Topic Space. The property &quot;use destination wildcard&quot; is not supported when a Topic Space is used.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification, the &quot;use destination wildcard&quot; was found not to be valid because a Topic Space is being used.
  </Explanation>
  <UserResponse>
    Ensure that &quot;use destination wildcard&quot; property is not set when using a Topic Space. Correct the value of the property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0904W" severity="W" prefix="yes">
  <MsgText pgmKey="NO_MBEAN_EXCEPTION_CWSIV0904" varFormat="Java">
    NO_MBEAN_EXCEPTION_CWSIV0904=CWSIV0904W: During an attempt to stop an MDB there were zero Message Endpoints that could be located for endpoint {0} which was listening to the destination {1}.
  </MsgText>
  <Explanation>
    The system cannot locate a message endpoint.
  </Explanation>
  <UserResponse>
    Check the status of the message endpoint using wsadmin scripting or the administrative console. If the message endpoint is active, pause the endpoint and investigate possible problems with the message-driven bean. Resume the endpoint when you are ready.
  </UserResponse>
</Message>
<Message ID="CWSIV0151E" severity="E" prefix="yes">
  <MsgText pgmKey="ACTIVE_CONTAINER_TRAN_CWSIV0151" varFormat="Java">
    ACTIVE_CONTAINER_TRAN_CWSIV0151=CWSIV0151E: There is a container-managed transaction on the thread.
  </MsgText>
  <Explanation>
    An attempt has been made to create a new SIUncoordinatedTransaction while there is a container-managed transaction on the thread.
  </Explanation>
  <UserResponse>
    Modify the application so that the call is made in an environment where there is no container-managed transaction on the thread.
  </UserResponse>
</Message>
<Message ID="CWSIV0512E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_TARGET_TYPE_CWSIV0512" varFormat="Java">
    INVALID_PROPERTY_TARGET_TYPE_CWSIV0512=CWSIV0512E: The following target type field on a Core SPI activation specification is invalid [{3}]. The values [{0}], [{1}] or [{2}] are expected.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the target type was found not to be valid.
  </Explanation>
  <UserResponse>
    Correct the value of the target type property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0778I" severity="I" prefix="yes">
  <MsgText pgmKey="ME_INITIALIZING_CWSIV0778" varFormat="Java">
    ME_INITIALIZING_CWSIV0778=CWSIV0778I: The local messaging engine {0} for bus {1} that is required by endpoint activation {2} is now available.
  </MsgText>
  <Explanation>
    The given endpoint activation was connecting remotely because no local messaging engines were enabled.  All remote connections are now closed.  When the local messaging engine is active, a new connection is attempted.
  </Explanation>
  <UserResponse>
    No action is required.
  </UserResponse>
</Message>
<Message ID="CWSIV0503E" severity="E" prefix="yes">
  <MsgText pgmKey="WLM_CLASSIFIER_REG_CWSIV0503" varFormat="Java">
    WLM_CLASSIFIER_REG_CWSIV0503=CWSIV0503E: An internal error has occurred during the registration of the WLM classifier for the core SPI resource adapter: {0}.
  </MsgText>
  <Explanation>
    During the registration of the WLM classifier for the core SPI resource adapter with the handler registry an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0773E" severity="E" prefix="yes">
  <MsgText pgmKey="RELOAD_FAILED_CWSIV0773" varFormat="Java">
    RELOAD_FAILED_CWSIV0773=CWSIV0773E: The exception {0} was thrown when processing the updated configuration for messaging engine {1} on bus {2} for endpoint activation {3}.
  </MsgText>
  <Explanation>
    When processing the updated configuration for the given messaging engine an exception was received.  Messages for the queue point on that messaging engine cannot be received by the corresponding message-driven bean.
  </Explanation>
  <UserResponse>
    See the exception for the cause.  After resolving the issue, restart the messaging engine, resource adapter, or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0051E" severity="E" prefix="yes">
  <MsgText pgmKey="INCORRECT_FACTORY_TYPE_CWSIV0051" varFormat="Java">
    INCORRECT_FACTORY_TYPE_CWSIV0051=CWSIV0051E: An internal error occurred. The connection factory returned from the JCA runtime {0} does not implement SICoreConnectionFactory.
  </MsgText>
  <Explanation>
    The connection factory returned from the JCA runtime did not implement SICoreConnectionFactory as expected.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0550E" severity="E" prefix="yes">
  <MsgText pgmKey="NO_METHOD_CWSIV0550" varFormat="Java">
    NO_METHOD_CWSIV0550=CWSIV0550E: An internal error occurred. The exception {1} was thrown by the message endpoint factory {0} when attempting to determine whether the onMessage method is transacted.
  </MsgText>
  <Explanation>
    The endpoint activation received an exception from the message endpoint factory indicating that there is no onMessage for this endpoint when trying to determine its transactionality.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0900E" severity="E" prefix="yes">
  <MsgText pgmKey="LISTENER_CREATION_CWSIV0900" varFormat="Java">
    LISTENER_CREATION_CWSIV0900=CWSIV0900E: The exception {0} was thrown while attempting to create a listener for destination {1} on bus {2} using connection {3}.
  </MsgText>
  <Explanation>
    An exception was created whilst the inbound resource adapter was attempting to create a listener for the given destination.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.  Resolve the issue then restart the application, resource adapter or messaging engine as appropriate.
  </UserResponse>
</Message>
<Message ID="CWSIV0501E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTIES_CWSIV0501" varFormat="Java">
    INVALID_PROPERTIES_CWSIV0501=CWSIV0501E: The following problems were found when validating the properties defined on the activation specification. The problems are {1}. The activation specification is : {0}
  </MsgText>
  <Explanation>
    During validation of the given activation specification one or more properties were determined to be incorrect.
  </Explanation>
  <UserResponse>
    Correct the values for the given properties in the administered activation specification, or in the message-driven bean&apos;s activation configuration, then start the application.
  </UserResponse>
</Message>
<Message ID="CWSIV0404E" severity="E" prefix="yes">
  <MsgText pgmKey="ACTIVE_LOCAL_TRAN_CWSIV0404" varFormat="Java">
    ACTIVE_LOCAL_TRAN_CWSIV0404=CWSIV0404E: An internal error occurred. There is already an active container local transaction.
  </MsgText>
  <Explanation>
    The container is attempting to begin a local transaction when there is already one active.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0700E" severity="E" prefix="yes">
  <MsgText pgmKey="CLONE_EXCEPTION_CWSIV0700" varFormat="Java">
    CLONE_EXCEPTION_CWSIV0700=CWSIV0700E: An internal error occurred. The exception {0} was received when attempting to clone the parent connection for session {1}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to clone a connection that would be returned from getConnection on the session to be passed to the endpoint.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0902W" severity="W" prefix="yes">
  <MsgText pgmKey="MESSAGE_ENDPOINT_PAUSED_AUTONOMICALLY_CWSIV0902" varFormat="Java">
    MESSAGE_ENDPOINT_PAUSED_AUTONOMICALLY_CWSIV0902=CWSIV0902W: The Message Endpoint {0} that was listening to the destination {1} has been paused by the system.
  </MsgText>
  <Explanation>
    The system paused the message endpoint because it detected a problem with the message-driven bean&apos;s message endpoint.
  </Explanation>
  <UserResponse>
    Investigate possible problems with the message-driven bean that could cause sequential errors. When you are ready to resume the message endpoint, use the administrative console. Alternatively, use the message endpoint MBean to resume the endpoint, passing to it the endpoint name in this message.
  </UserResponse>
</Message>
<Message ID="CWSIV0510E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_DELETION_MODE_CWSIV0510" varFormat="Java">
    INVALID_PROPERTY_DELETION_MODE_CWSIV0510=CWSIV0510E: The following deletion mode on a Core SPI activation specification is invalid [{3}]. The values [{0}] or [{1}] or [{2}] are expected.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the deletion mode was found not to be valid
  </Explanation>
  <UserResponse>
    Correct the value of the deletion mode property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV1153W" severity="W" prefix="yes">
  <MsgText pgmKey="UNABLE_TO_LOCATE_SERVER_CWSIV1153" varFormat="Java">
    UNABLE_TO_LOCATE_SERVER_CWSIV1153=CWSIV1153W: Unable to read the custom property MessageLockExpiry as Platform Messaging was unable to locate the server. The default value of {0} will be used
  </MsgText>
  <Explanation>
    The inbound resource adapter could not find the server so the property MessageLockExpiry was assigned a default value.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0053E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_TYPE_CWSIV0053" varFormat="Java">
    INVALID_PROPERTY_TYPE_CWSIV0053=CWSIV0053E: The connection factory property {0} is not of the required type {1}.
  </MsgText>
  <Explanation>
    The property map passed to the getConnectionFactory method on SICoreConnectionFactorySelector contained a value for the given property that was not of the required type.
  </Explanation>
  <UserResponse>
    Ensure that the set of properties passed to the getConnectionFactory method on SICoreConnectionFactorySelector is valid.
  </UserResponse>
</Message>
<Message ID="CWSIV0702E" severity="E" prefix="yes">
  <MsgText pgmKey="OUT_OF_SCOPE_CWSIV0702" varFormat="Java">
    OUT_OF_SCOPE_CWSIV0702=CWSIV0702E: The session is no longer in scope.
  </MsgText>
  <Explanation>
    The session passed to the onMessage method of a Platform Messaging core SPI message-driven bean cannot be used once the method has completed.
  </Explanation>
  <UserResponse>
    Remove the offending call and, if required, create a separate Platform Messaging core SPI session.
  </UserResponse>
</Message>
<Message ID="CWSIV0152E" severity="E" prefix="yes">
  <MsgText pgmKey="XARESOURCE_NOT_SUPPORTED_CWSIV0152" varFormat="Java">
    XARESOURCE_NOT_SUPPORTED_CWSIV0152=CWSIV0152E: The creation of an SIXAResource is not supported.
  </MsgText>
  <Explanation>
    The creation of an SIXAResource is not supported when using the RA_CONNECTION implementation of the Platform Messaging core SPI because global transactions are handled by the resource adapter.
  </Explanation>
  <UserResponse>
    If the application must handle global transactions explicitly then use a different implementation of the Platform Messaging core SPI, otherwise remove the call to getSIXAResource.
  </UserResponse>
</Message>
<Message ID="CWSIV0156E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_CONNECTION_CWSIV0156" varFormat="Java">
    INVALID_CONNECTION_CWSIV0156=CWSIV0156E: The connection has been invalidated.
  </MsgText>
  <Explanation>
    A previous error has caused the connection to be no longer valid.
  </Explanation>
  <UserResponse>
    Check error logs to determine cause of previous error.  The application should create a new connection.
  </UserResponse>
</Message>
<Message ID="CWSIV0352E" severity="E" prefix="yes">
  <MsgText pgmKey="NULL_REQUEST_INFO_CWSIV0352" varFormat="Java">
    NULL_REQUEST_INFO_CWSIV0352=CWSIV0352E: An internal error occurred. Connection request information is required to create a managed connection.
  </MsgText>
  <Explanation>
    The connection manager has attempted to create a managed connection without specifying any connection request information.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0350E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_FACTORY_ERROR_CWSIV0350" varFormat="Java">
    CONNECTION_FACTORY_ERROR_CWSIV0350=CWSIV0350E: An internal error occurred. The exception {0} was thrown while attempting to create a core SPI connection factory.
  </MsgText>
  <Explanation>
    An exception was created while attempting to create a core SPI connection factory using the factory type TRM_CONNECTION.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0906W" severity="W" prefix="yes">
  <MsgText pgmKey="MAXSEQUENTIALMESSAGEFAILURE_CONFIG_VALUE_CHANGED_CWSIV0906" varFormat="Java">
    MAXSEQUENTIALMESSAGEFAILURE_CONFIG_VALUE_CHANGED_CWSIV0906=CWSIV0906W: The MDB maximum sequential message failure configuration value has been changed from the value {0} to {1}.
  </MsgText>
  <Explanation>
    The maximum sequential message failure value has changed because strict message ordering has been turned on.
  </Explanation>
  <UserResponse>
    No action is necessary unless you require the sequential message failure function. If you require the sequential message failure function, turn off strict message ordering.
  </UserResponse>
</Message>
<Message ID="CWSIV0651E" severity="E" prefix="yes">
  <MsgText pgmKey="BEFORE_DELIVERY_CWSIV0651" varFormat="Java">
    BEFORE_DELIVERY_CWSIV0651=CWSIV0651E: An internal error occurred. The exception {0} was received when attempting to invoke beforeDelivery on endpoint {1}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to invoke beforeDelivery on an endpoint prior to calling onMessage.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0408E" severity="E" prefix="yes">
  <MsgText pgmKey="XARESOURCE_CREATE_CWSIV0408" varFormat="Java">
    XARESOURCE_CREATE_CWSIV0408=CWSIV0408E: An internal error occurred. The exception {0} was thrown while attempting to obtain an SIXAResource.
  </MsgText>
  <Explanation>
    An exception was created while attempting to obtain an SIXAResource.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0157E" severity="E" prefix="yes">
  <MsgText pgmKey="CONTAINER_TRAN_CWSIV0157" varFormat="Java">
    CONTAINER_TRAN_CWSIV0157=CWSIV0157E: An internal error occurred.  The exception {0} was thrown while attempt to obtain the current container transaction.
  </MsgText>
  <Explanation>
    While attempting to obtain the current container transaction an exception was received.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0163E" severity="E" prefix="yes">
  <MsgText pgmKey="CONTAINER_ROLLBACK_FAILED_CWSIV0163" varFormat="Java">
    CONTAINER_ROLLBACK_FAILED_CWSIV0163=CWSIV0163E: An internal error occurred.  The exception {0} was thrown while the container was attempting to roll back an application local transaction.
  </MsgText>
  <Explanation>
    The container has detected an outstanding application local transaction at the end of a sharing scope and an exception was created while attempting to roll it back.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0801E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_FAILED_CWSIV0801" varFormat="Java">
    CREATE_CONNECTION_FAILED_CWSIV0801=CWSIV0801E: The exception {0} was thrown during the creation of a connection to messaging engine {1} on bus {2}.
  </MsgText>
  <Explanation>
    The inbound core SPI resource adapter was attempting to create a connection for the given messaging engine when it received an exception.  Messages from destinations localized on that messaging engine will not be received by the message-driven bean.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0055E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_CWSIV0055" varFormat="Java">
    INVALID_PROPERTY_CWSIV0055=CWSIV0055E: The value {0} is not valid for the connection factory property {1}. Valid values are {2} and {3}.
  </MsgText>
  <Explanation>
    The property map passed to the getConnectionFactory method on SICoreConnectionFactorySelector contained an incorrect value for the given property.
  </Explanation>
  <UserResponse>
    Ensure that the set of properties passed to the getConnectionFactory method on SICoreConnectionFactorySelector is valid.
  </UserResponse>
</Message>
<Message ID="CWSIV0052E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_CWSIV0052" varFormat="Java">
    INVALID_PROPERTY_CWSIV0052=CWSIV0052E: The value {0} is not valid for the connection factory property {1}. Valid values are {2} and {3}.
  </MsgText>
  <Explanation>
    The property map passed to the getConnectionFactory method on SICoreConnectionFactorySelector contained an incorrect value for the given property.
  </Explanation>
  <UserResponse>
    Ensure that the set of properties passed to the getConnectionFactory method on SICoreConnectionFactorySelector is valid.
  </UserResponse>
</Message>
<Message ID="CWSIV0753E" severity="E" prefix="yes">
  <MsgText pgmKey="DESTINATION_LOCALITY_CWSIV0753" varFormat="Java">
    DESTINATION_LOCALITY_CWSIV0753=CWSIV0753E: An internal error occurred. The following exception was thrown when attempting to determine the set of queue points for the destination {1}: {0}.
  </MsgText>
  <Explanation>
    An unexpected exception was received when attempting to determine the set of messaging engines with queue points for the given destination.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0509E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_MAXBATCH_CWSIV0509" varFormat="Java">
    INVALID_PROPERTY_MAXBATCH_CWSIV0509=CWSIV0509E: The maximum batch size on a Core SPI activation specification must be given a positive value
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the maximum batch size was found not to be valid
  </Explanation>
  <UserResponse>
    Correct the value of the maximum batch size property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0554E" severity="E" prefix="yes">
  <MsgText pgmKey="ENDPOINT_DEACTIVATED_CWSIV0554" varFormat="Java">
    ENDPOINT_DEACTIVATED_CWSIV0554=CWSIV0554E: An internal error occurred. An attempt was made to obtain a connection to the messaging engine with UUID {0} on bus {1} after the endpoint {2} has been deactivated.
  </MsgText>
  <Explanation>
    A request was made for a connection to the given messaging engine but the endpoint activation has been deactivated.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0757E" severity="E" prefix="yes">
  <MsgText pgmKey="NOT_FOUND_CWSIV0757" varFormat="Java">
    NOT_FOUND_CWSIV0757=CWSIV0757E: The destination {0} on bus {1} was not found.
  </MsgText>
  <Explanation>
    The destination configured on the message-driven bean does not exist in the given bus.
  </Explanation>
  <UserResponse>
    Check the definition of the destination on the message-driven bean&apos;s activation specification or bindings.
  </UserResponse>
</Message>
<Message ID="CWSIV0903W" severity="W" prefix="yes">
  <MsgText pgmKey="INVOKE_MBEAN_EXCEPTION__CWSIV0903" varFormat="Java">
    INVOKE_MBEAN_EXCEPTION__CWSIV0903=CWSIV0903W: The Message Endpoint {0} that was listening to the destination {1} was attempted to be paused but the invoke of the MBean failed with the following exception {2}.
  </MsgText>
  <Explanation>
    The system detected a problem with a message endpoint&apos;s message-driven bean but the attempt to pause the message endpoint failed.
  </Explanation>
  <UserResponse>
    Check the status of the message endpoint using wsadmin scripting or the administrative console. If the message endpoint is active, pause the endpoint and investigate possible problems with the message-driven bean. Resume the endpoint when you are ready.
  </UserResponse>
</Message>
<Message ID="CWSIV0507E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_DURSUBHOME_CWSIV0507" varFormat="Java">
    INVALID_PROPERTY_DURSUBHOME_CWSIV0507=CWSIV0507E: The durable subscription home on a Core SPI activation specification must have a value when using durable subscriptions.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the durable subscription home was found not to be valid
  </Explanation>
  <UserResponse>
    Correct the value of the durable subscription home property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0451E" severity="E" prefix="yes">
  <MsgText pgmKey="UNEXPECTED_ACTIVATION_SPEC_CWSIV0451" varFormat="Java">
    UNEXPECTED_ACTIVATION_SPEC_CWSIV0451=CWSIV0451E: An internal error occurred. The activation specification {0} passed on endpoint activation was not of the expected type {1}.
  </MsgText>
  <Explanation>
    The activation specification passed on endpoint activation was not of the type expected by the resource adapter.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV9999E" severity="E" prefix="yes">
  <MsgText pgmKey="TEMPORARY_CWSIV9999" varFormat="Java">
    TEMPORARY_CWSIV9999=CWSIV9999E: {0}
  </MsgText>
  <Explanation>
    If the message does not give sufficient information, see the accompanying error messages for further information.
  </Explanation>
  <UserResponse>
    See the accompanying error messages for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0604E" severity="E" prefix="yes">
  <MsgText pgmKey="REQUEST_METRICS_CWSIV0604" varFormat="Java">
    REQUEST_METRICS_CWSIV0604=CWSIV0604E: An internal error occurred. The exception {0} was received when attempting to obtain the request metrics instance.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to obtain the request metrics instance.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0162E" severity="E" prefix="yes">
  <MsgText pgmKey="CONTAINER_COMMIT_FAILED_CWSIV0162" varFormat="Java">
    CONTAINER_COMMIT_FAILED_CWSIV0162=CWSIV0162E: An internal error occurred.  The exception {0} was thrown while the container was attempting to commit an application local transaction.
  </MsgText>
  <Explanation>
    The container has detected an outstanding application local transaction at the end of a sharing scope and an exception was created while attempting to commit it.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0607E" severity="E" prefix="yes">
  <MsgText pgmKey="MESSAGE_LIST_INCORRECT_CWSIV0607" varFormat="Java">
    MESSAGE_LIST_INCORRECT_CWSIV0607=CWSIV0607E: An internal error occurred. When attempting to delete the message handle {2} under transaction {3}, the list of messages {1} was expected to contain 1 message but instead contained {0} messages
  </MsgText>
  <Explanation>
    The resource adapter encountered a problem while attempting to delete a message handle
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0506E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_SHARE_DURSUB_CWSIV0506" varFormat="Java">
    INVALID_PROPERTY_SHARE_DURSUB_CWSIV0506=CWSIV0506E: The following share durable subscription field on a Core SPI activation specification is invalid [{3}]. The values [{0}], [{1}] or [{2}] are expected.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the share durable subscription was found not to be valid
  </Explanation>
  <UserResponse>
    Correct the value of the share durable subscription property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0701E" severity="E" prefix="yes">
  <MsgText pgmKey="NOT_SUPPORTED_CWSIV0701" varFormat="Java">
    NOT_SUPPORTED_CWSIV0701=CWSIV0701E: Use of the method {0} is not supported.
  </MsgText>
  <Explanation>
    The given method cannot be invoked on the session passed to the onMessage method of a Platform Messaging core SPI message-driven bean.
  </Explanation>
  <UserResponse>
    Remove the offending call and, if required, create a separate Platform Messaging core SPI session.
  </UserResponse>
</Message>
<Message ID="CWSIV0605W" severity="W" prefix="yes">
  <MsgText pgmKey="MESSAGE_ENDPOINT_SHOULD_BE_DEACTIVATED_CWSIV0605" varFormat="Java">
    MESSAGE_ENDPOINT_SHOULD_BE_DEACTIVATED_CWSIV0605=CWSIV0605W: The Message Endpoint {0} that was listening to the destination {1} should be deactivated as the the maximum number of sequential failures was reached.
  </MsgText>
  <Explanation>
    The System has determined that there is a possible problem with the MDB associated with the message endpoint.
  </Explanation>
  <UserResponse>
    Investigate possible problems with the MDB that could cause sequential failures. The message endpoint can be deactivated to stop further errors occurring, use the Message Endpoint MBean passing the endpoint name in this message to deactivate the endpoint or stop the application that contains the Message Driven Bean.
  </UserResponse>
</Message>
<Message ID="CWSIV0755E" severity="E" prefix="yes">
  <MsgText pgmKey="INCORRECT_TYPE_CWSIV0755" varFormat="Java">
    INCORRECT_TYPE_CWSIV0755=CWSIV0755E: The destination {0} on bus {1} is of the type {3} not the required type {2}.
  </MsgText>
  <Explanation>
    The destination type defined on the message-driven bean&apos;s activation specification does not match the type of the configured destination.
  </Explanation>
  <UserResponse>
    Check that the message-driven bean&apos;s activation specification is configured with the correct destination, type or both.
  </UserResponse>
</Message>
<Message ID="CWSIV1202E" severity="E" prefix="yes">
  <MsgText pgmKey="REGISTER_SYNC_CWSIV1202" varFormat="Java">
    REGISTER_SYNC_CWSIV1202=CWSIV1202E: An internal error occurred. The exception {1} was received when attempting to register the synchronization {0}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to register the given synchronization with the transaction manager.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV1150E" severity="E" prefix="yes">
  <MsgText pgmKey="RETRIEVE_MESSAGES_CWSIV1150" varFormat="Java">
    RETRIEVE_MESSAGES_CWSIV1150=CWSIV1150E: An internal error occurred. The exception {0} was thrown while attempting to obtain messages from the enumeration {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to retrieve the messages from an enumeration when an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0154E" severity="E" prefix="yes">
  <MsgText pgmKey="LAZY_ENLIST_NOT_SUPPORTED_CWSIV0154" varFormat="Java">
    LAZY_ENLIST_NOT_SUPPORTED_CWSIV0154=CWSIV0154E: An internal error occurred. The connection manager {0} does not support lazy enlistment.
  </MsgText>
  <Explanation>
    The current connection has been dissociated from its managed connection but the connection manager does not support lazy enlistment for the re-association to take place.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0504E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_BUSNAME_CWSIV0504" varFormat="Java">
    INVALID_PROPERTY_BUSNAME_CWSIV0504=CWSIV0504E: The bus name on a Core SPI activation specification must be given a value
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the bus name was found not to be valid.
  </Explanation>
  <UserResponse>
    Correct the value of the bus name property on the activation specification then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0768I" severity="I" prefix="yes">
  <MsgText pgmKey="LAST_ME_CWSIV0768" varFormat="Java">
    LAST_ME_CWSIV0768=CWSIV0768I: The last local messaging engine {0} on bus {1} used by endpoint activation {2} is stopping.
  </MsgText>
  <Explanation>
    The given endpoint activation was using a messaging engine that has now been stopped.  There are no other active messaging engines to connect to.  The associated message-driven bean will start to receive messages again when a suitable messaging engine becomes available.
  </Explanation>
  <UserResponse>
    No action is required.
  </UserResponse>
</Message>
<Message ID="CWSIV0161E" severity="E" prefix="yes">
  <MsgText pgmKey="UNRECOGNISED_TRAN_CWSIV0161" varFormat="Java">
    UNRECOGNISED_TRAN_CWSIV0161=CWSIV0161E: The transaction parameter {0} was not of a recognized type.
  </MsgText>
  <Explanation>
    The object passed as the transaction parameter was not of a recognized type.
  </Explanation>
  <UserResponse>
    Ensure that the transaction parameter is either null, an SIUncoordinatedTransaction obtained from this connection or an SibRaAutoCommitTransaction.
  </UserResponse>
</Message>
<Message ID="CWSIV0601E" severity="E" prefix="yes">
  <MsgText pgmKey="UNLOCK_EXCEPTION_CWSIV0601" varFormat="Java">
    UNLOCK_EXCEPTION_CWSIV0601=CWSIV0601E: An internal error occurred. The exception {0} was received when attempting to unlock the messages {1}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to unlock a set of messages.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0050E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_FACTORY_EXCEPTION_CWSIV0050" varFormat="Java">
    CONNECTION_FACTORY_EXCEPTION_CWSIV0050=CWSIV0050E: An internal error occurred. The exception {0} was received from the JCA runtime while attempting to obtain a connection factory.
  </MsgText>
  <Explanation>
    While attempting to obtain an SICoreConnectionFactory through the JCA runtime, an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0787I" severity="I" prefix="yes">
  <MsgText pgmKey="TARGETTED_CONNECTION_FAILED_CWSIV0787" varFormat="Java">
    TARGETTED_CONNECTION_FAILED_CWSIV0787=CWSIV0787I: Failed to create a connection to a messaging engine when specifying a target to connect to. The target was of type {0} had a significance of {1} and was named {2}. The target bus was {3}
  </MsgText>
  <Explanation>
    The system failed to connect to a messaging engine when given a set of target information. This may be a temporary connection problem if no messaging engine that matches the target data is available or this may be a configuration issue with the activation specification being used.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus that matches the supplied target information is available.  The resource adapter automatically attempts to connect to the bus periodically. If the messaging engine is available then check the activation config settings are correct, particularly the busname and the  target information.
  </UserResponse>
</Message>
<Message ID="CWSIV0355E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_MANAGED_CONNECTION_CWSIV0355" varFormat="Java">
    CREATE_MANAGED_CONNECTION_CWSIV0355=CWSIV0355E: An internal error occurred. Whilst creating the managed connection the following exception was thrown: {0}
  </MsgText>
  <Explanation>
    An exception was created while attempting to create a managed connection.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV1155W" severity="W" prefix="yes">
  <MsgText pgmKey="NEGATIVE_MESSAGELOCKEXPIRY_CWSIV1155" varFormat="Java">
    NEGATIVE_MESSAGELOCKEXPIRY_CWSIV1155=CWSIV1155W: The value for the MessageLockExpiry appears to be {0}, this value can not be negative. The default of {1} will be used
  </MsgText>
  <Explanation>
    Negative values are not allowed for the message lock expiry time
  </Explanation>
  <UserResponse>
    Check the value assigned to the custom property MessageLockExpiry is either positive or zero, then restart the server for the changes to take effect.
  </UserResponse>
</Message>
<Message ID="CWSIV1000E" severity="E" prefix="yes">
  <MsgText pgmKey="WAS_ENDPOINT_FACTORY_CWSIV1000" varFormat="Java">
    WAS_ENDPOINT_FACTORY_CWSIV1000=CWSIV1000E: An internal error occurred. The message endpoint factory {0} passed to the resource adapter did not implement the expected interface {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter requires the message endpoint factory to implement the given interface in order to obtain the unique name of the message-driven bean.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0353E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_CLONE_CWSIV0353" varFormat="Java">
    CONNECTION_CLONE_CWSIV0353=CWSIV0353E: An internal error occurred. The exception {0} was thrown while attempting to clone a connection to the messaging engine.
  </MsgText>
  <Explanation>
    An exception was created while attempting to clone a connection to the messaging engine during the creation of a managed connection.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV1151E" severity="E" prefix="yes">
  <MsgText pgmKey="GET_ID_CWSIV1151" varFormat="Java">
    GET_ID_CWSIV1151=CWSIV1151E: An internal error occurred. The exception {0} was thrown while attempting to obtain the identifier for the session {0} created from connection {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to obtain the identifier for a session when an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0776W" severity="W" prefix="yes">
  <MsgText pgmKey="CONNECTION_ERROR_CWSIV0776" varFormat="Java">
    CONNECTION_ERROR_CWSIV0776=CWSIV0776W: A connection to remote messaging engine {0} on bus {1} for endpoint activation {2} failed with exception {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter received an exception for an existing connection to a  messaging engine.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV1101W" severity="W" prefix="yes">
  <MsgText pgmKey="MAXCONCURRENCY_CONFIG_VALUE_CHANGED_CWSIV1101" varFormat="Java">
    MAXCONCURRENCY_CONFIG_VALUE_CHANGED_CWSIV1101=CWSIV1101W: The MDB maximum concurrency configuration value has been changed from the value {0} to {1}.
  </MsgText>
  <Explanation>
    The maximum concurrency value has changed because strict message ordering has been turned on.
  </Explanation>
  <UserResponse>
    No action is required unless concurrent message-driven beans are required. If so then turn off strict message ordering.
  </UserResponse>
</Message>
<Message ID="CWSIV0153E" severity="E" prefix="yes">
  <MsgText pgmKey="CLONE_NOT_SUPPORTED_CWSIV0153" varFormat="Java">
    CLONE_NOT_SUPPORTED_CWSIV0153=CWSIV0153E: The cloning of a connection is not supported.
  </MsgText>
  <Explanation>
    The cloning of a connection is not supported when using the RA_CONNECTION implementation of the core SPI.
  </Explanation>
  <UserResponse>
    Consider whether cloning of a connection is required or whether simply creating another connection would suffice.
  </UserResponse>
</Message>
<Message ID="CWSIV0850E" severity="E" prefix="yes">
  <MsgText pgmKey="UNEXPECTED_ENDPOINT_CWSIV0850" varFormat="Java">
    UNEXPECTED_ENDPOINT_CWSIV0850=CWSIV0850E: An internal error occurred. The message endpoint {0} does not implement the expected interface {1}.
  </MsgText>
  <Explanation>
    The message endpoint factory has returned a message endpoint that does not implement the SibRaMessageListener interface as expected.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0807E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_ERROR_CWSIV0807" varFormat="Java">
    CONNECTION_ERROR_CWSIV0807=CWSIV0807E: The exception {0} was thrown on a connection to messaging engine {1} for endpoint activation {2}.
  </MsgText>
  <Explanation>
    An exception was received for the given connection.  The corresponding message-driven bean will be deactivated and will receive no further messages.
  </Explanation>
  <UserResponse>
    See exception for cause.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0767E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_ERROR_CWSIV0767" varFormat="Java">
    CONNECTION_ERROR_CWSIV0767=CWSIV0767E: The exception {0} was thrown on a connection to messaging engine {1} for endpoint activation {2}.
  </MsgText>
  <Explanation>
    An exception was received for the given connection.  The corresponding message-driven bean will be deactivated and will receive no further messages.
  </Explanation>
  <UserResponse>
    See exception for cause.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0513E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_TARGET_SIGNIFICANCE_CWSIV0513" varFormat="Java">
    INVALID_PROPERTY_TARGET_SIGNIFICANCE_CWSIV0513=CWSIV0513E: The following target significance field on a Core SPI activation specification is invalid [{2}]. The values [{0}] or [{1}] are expected.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the target significance was found not to be valid
  </Explanation>
  <UserResponse>
    Correct the value of the target significance property on the activation specification then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0806E" severity="E" prefix="yes">
  <MsgText pgmKey="SESSION_ERROR_CWSIV0806" varFormat="Java">
    SESSION_ERROR_CWSIV0806=CWSIV0806E: The exception {0} was thrown to the consumer for destination {1} on messaging engine {2} on bus {3} for endpoint activation {4}.
  </MsgText>
  <Explanation>
    An asynchronous exception was received for the given consumer.  The corresponding message-driven bean will be deactivated and will receive no further messages.
  </Explanation>
  <UserResponse>
    See exception for cause.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0514E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_PROVIDER_ENDPOINTS_CWSIV0514" varFormat="Java">
    INVALID_PROPERTY_PROVIDER_ENDPOINTS_CWSIV0514=CWSIV0514E: The provider endpoints were set to {0} on a Core SPI activation specification. Provider endpoints are not supported when the property &quot;use server subject&quot; is set.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification, the provider endpoint was found not to be valid because the use server subject property is set.
  </Explanation>
  <UserResponse>
    Please ensure that provider endpoints property is not set if use server subject is set. Correct the value of the property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0766E" severity="E" prefix="yes">
  <MsgText pgmKey="SESSION_ERROR_CWSIV0766" varFormat="Java">
    SESSION_ERROR_CWSIV0766=CWSIV0766E: The exception {0} was thrown to the consumer for destination {1} on messaging engine {2} on bus {3} for endpoint activation {4}.
  </MsgText>
  <Explanation>
    An asynchronous exception was received for the given consumer.  The corresponding message-driven bean will be deactivated and will receive no further messages.
  </Explanation>
  <UserResponse>
    See exception for cause.  After resolving issue, restart messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0101E" severity="E" prefix="yes">
  <MsgText pgmKey="INCORRECT_CONNECTION_TYPE_CWSIV0101" varFormat="Java">
    INCORRECT_CONNECTION_TYPE_CWSIV0101=CWSIV0101E: An internal error occurred. The JCA connection manager returned a connection {0} that was not of the expected type {1}.
  </MsgText>
  <Explanation>
    While attempting to obtain a connection through the JCA connection manager a connection of an unexpected type was returned.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0786I" severity="I" prefix="yes">
  <MsgText pgmKey="ME_TERMINATED_CWSIV0786" varFormat="Java">
    ME_TERMINATED_CWSIV0786=CWSIV0786I: The messaging engine {0} on bus {1} has terminated.
  </MsgText>
  <Explanation>
    The inbound resource adapter received notification that the messaging engine to which it was connected has terminated.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV0780W" severity="W" prefix="yes">
  <MsgText pgmKey="ME_TERMINATED_CWSIV0780" varFormat="Java">
    ME_TERMINATED_CWSIV0780=CWSIV0780W: The remote messaging engine {0} on bus {1} to which endpoint activation {2} was connected has terminated.
  </MsgText>
  <Explanation>
    The inbound resource adapter received notification that the remote messaging engine to which it was connected has terminated.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV0961E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0961" varFormat="Java">
    CREATE_CONNECTION_CWSIV0961=CWSIV0961E: The authorization exception {0} was thrown while attempting to create a connection to the bus {1} using the activation specification {2}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an authorization exception was received.
  </Explanation>
  <UserResponse>
    Check that the authentication alias on the activation specification, that the message-driven bean is configured to use, is authorized to connect to bus.
  </UserResponse>
</Message>
<Message ID="CWSIV0960E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0960" varFormat="Java">
    CREATE_CONNECTION_CWSIV0960=CWSIV0960E: The authorization exception {0} was thrown while attempting to create a connection to the bus {1} using the activation specification {2}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an authorization exception was received.
  </Explanation>
  <UserResponse>
    Ensure that a correct authentication alias is setup on the activation specification that the message-driven bean is configured to use.
  </UserResponse>
</Message>
<Message ID="CWSIV1100E" severity="E" prefix="yes">
  <MsgText pgmKey="RETRIEVE_MESSAGES_CWSIV1100" varFormat="Java">
    RETRIEVE_MESSAGES_CWSIV1100=CWSIV1100E: An internal error occurred. The exception {0} was thrown while attempting to obtain messages from the enumeration {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to retrieve the messages from an enumeration when an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0756E" severity="E" prefix="yes">
  <MsgText pgmKey="UNKNOWN_TYPE_CWSIV0756" varFormat="Java">
    UNKNOWN_TYPE_CWSIV0756=CWSIV0756E: An internal error occurred. The destination {0} on bus {1} has a definition of an unexpected type.
  </MsgText>
  <Explanation>
    The given destination was not a local, a foreign or an alias destination.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0785I" severity="I" prefix="yes">
  <MsgText pgmKey="ME_QUIESCING_CWSIV0785" varFormat="Java">
    ME_QUIESCING_CWSIV0785=CWSIV0785I: The messaging engine {0} on bus {1} is quiescing.
  </MsgText>
  <Explanation>
    The inbound resource adapter received notification that the messaging engine to which it was connected is quiescing and has disconnected.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV0781W" severity="W" prefix="yes">
  <MsgText pgmKey="ME_QUIESCING_CWSIV0781" varFormat="Java">
    ME_QUIESCING_CWSIV0781=CWSIV0781W: The remote messaging engine {0} on bus {1} to which endpoint activation {2} was connected is quiescing.
  </MsgText>
  <Explanation>
    The inbound resource adapter received notification that the remote messaging engine to which it was connected is quiescing and has disconnected.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV0758E" severity="E" prefix="yes">
  <MsgText pgmKey="UNEXPECTED_EXCEPTION_CWSIV0758" varFormat="Java">
    UNEXPECTED_EXCEPTION_CWSIV0758=CWSIV0758E: An internal error occurred. The following exception was thrown when attempting to obtain the definition of destination {0} on bus {1}: {2}.
  </MsgText>
  <Explanation>
    An unexpected exception was received when attempting to obtain the definition of the given destination.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0959E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0959" varFormat="Java">
    CREATE_CONNECTION_CWSIV0959=CWSIV0959E: The authorization exception {0} was thrown while attempting to create a connection to messaging engine {1} using the activation specification {2}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an authorization exception was received.
  </Explanation>
  <UserResponse>
    Check that the authentication alias on the activation specification, that the message-driven bean is configured to use, is authorized to connect to the messaging engine.
  </UserResponse>
</Message>
<Message ID="CWSIV0958E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0958" varFormat="Java">
    CREATE_CONNECTION_CWSIV0958=CWSIV0958E: The authorization exception {0} was thrown while attempting to create a connection to messaging engine {1} using the activation specification {2}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an authorization exception was received.
  </Explanation>
  <UserResponse>
    Ensure that a correct authentication alias is setup on the activation specification that the message-driven bean is configured to use.
  </UserResponse>
</Message>
<Message ID="CWSIV0957E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0957" varFormat="Java">
    CREATE_CONNECTION_CWSIV0957=CWSIV0957E: The authentication exception {0} was thrown while attempting to get the WebSphere Application Server Subject.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection using the server subject, but couldn&apos;t get the subject.
  </Explanation>
  <UserResponse>
    Check Application Server security settings are configured correctly.
  </UserResponse>
</Message>
<Message ID="CWSIV0955E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0955" varFormat="Java">
    CREATE_CONNECTION_CWSIV0955=CWSIV0955E: The authentication exception {0} was thrown while attempting to create a connection to messaging engine {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an authentication exception was received.
  </Explanation>
  <UserResponse>
    Ensure that the correct user name and password are supplied on the ActivationSpec that the message-driven bean is configured to use
  </UserResponse>
</Message>
<Message ID="CWSIV0954E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0954" varFormat="Java">
    CREATE_CONNECTION_CWSIV0954=CWSIV0954E: The authentication exception {0} was thrown while attempting to create a connection on factory {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an authentication exception was received.
  </Explanation>
  <UserResponse>
    Ensure that the correct user name and password are supplied on the ActivationSpec that the message-driven bean is configured to use
  </UserResponse>
</Message>
<Message ID="CWSIV1200E" severity="E" prefix="yes">
  <MsgText pgmKey="BEFORE_DELIVERY_CWSIV1200" varFormat="Java">
    BEFORE_DELIVERY_CWSIV1200=CWSIV1200E: An internal error occurred. The exception {0} was received when attempting to invoke beforeDelivery on endpoint {1}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to invoke beforeDelivery on an endpoint prior to calling onMessage.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0951E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0951" varFormat="Java">
    CREATE_CONNECTION_CWSIV0951=CWSIV0951E: An internal error occurred. The exception {0} was thrown while attempting to create a connection to messaging engine {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0950E" severity="E" prefix="yes">
  <MsgText pgmKey="CREATE_CONNECTION_CWSIV0950" varFormat="Java">
    CREATE_CONNECTION_CWSIV0950=CWSIV0950E: An internal error occurred. The exception {0} was thrown while attempting to create a connection on factory {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to create a connection when an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0159E" severity="E" prefix="yes">
  <MsgText pgmKey="INCORRECT_LOCAL_TRAN_CWSIV0159" varFormat="Java">
    INCORRECT_LOCAL_TRAN_CWSIV0159=CWSIV0159E: The active SIUncoordinatedTransaction associated with this connection was not passed.
  </MsgText>
  <Explanation>
    An attempt has been made to use an SIUncoordinatedTransaction as the transaction parameter when there is a different active SIUncoordinatedTransaction associated with this connection.
  </Explanation>
  <UserResponse>
    Ensure that the application is passing the current active SIUncoordinatedTransaction associated with the connection or null if the operation should be performed outside of the transaction.
  </UserResponse>
</Message>
<Message ID="CWSIV1053E" severity="E" prefix="yes">
  <MsgText pgmKey="NO_POOL_CWSIV1053" varFormat="Java">
    NO_POOL_CWSIV1053=CWSIV1053E: An internal error occurred. The inbound resource adapter failed to locate an endpoint activation pool for {0} so was unable to retreive an endpoint activation
  </MsgText>
  <Explanation>
    The inbound resource adapter could not get an endpoint activation from the pool because it could not locate the pool
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0804E" severity="E" prefix="yes">
  <MsgText pgmKey="ADD_DESTINATION_LISTENER_FAILED_CWSIV0804" varFormat="Java">
    ADD_DESTINATION_LISTENER_FAILED_CWSIV0804=CWSIV0804E: The exception {0} was thrown during the addition of a destination listener for messaging engine {1} on bus {2}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was attempting to add a destination listener for the given messaging engine when it received an exception.  Messages from queue points on that messaging engine will not be received by the message-driven bean.
  </Explanation>
  <UserResponse>
    See the linked exception for the cause.  After resolving the issue, restart the messaging engine, resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0953E" severity="E" prefix="yes">
  <MsgText pgmKey="LISTENER_CLOSED_CWSIV0953" varFormat="Java">
    LISTENER_CLOSED_CWSIV0953=CWSIV0953E: An internal error occurred. An attempt was made to create a dispatcher on a connection that has been closed.
  </MsgText>
  <Explanation>
    The messaging engine connection received a request to create a dispatcher but has already been closed.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0952E" severity="E" prefix="yes">
  <MsgText pgmKey="LISTENER_CLOSED_CWSIV0952" varFormat="Java">
    LISTENER_CLOSED_CWSIV0952=CWSIV0952E: An internal error occurred. An attempt was made to create a listener on a connection that has been closed.
  </MsgText>
  <Explanation>
    The messaging engine connection received a request to create a listener but has already been closed.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0808W" severity="W" prefix="yes">
  <MsgText pgmKey="SESSION_DROPPED_CWSIV0808" varFormat="Java">
    SESSION_DROPPED_CWSIV0808=CWSIV0808W: Consumption of messages from the destination {0} on messaging engine {1} on bus {2} has stopped because the session was dropped. The exception was {3}
  </MsgText>
  <Explanation>
    The session was dropped for the reason stated in the exception. This might be because the specified destination has been deleted or marked as send-only.  The corresponding message-driven bean will be deactivated and will receive no further messages.
  </Explanation>
  <UserResponse>
    If this warning was not expected, resolve the issue then restart the application, resource adapter or messaging engine as appropriate.
  </UserResponse>
</Message>
<Message ID="CWSIV0403E" severity="E" prefix="yes">
  <MsgText pgmKey="UNRECOGNISED_CONNECTION_CWSIV0403" varFormat="Java">
    UNRECOGNISED_CONNECTION_CWSIV0403=CWSIV0403E: An internal error occurred. The connection object {0} was not of the expected type {1}.
  </MsgText>
  <Explanation>
    The object passed as the connection parameter was not of the type expected by this resource adapter.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV1050E" severity="E" prefix="yes">
  <MsgText pgmKey="MSG_TOKEN_CWSIV1050" varFormat="Java">
    MSG_TOKEN_CWSIV1050=CWSIV1050E: An internal error occurred. The request object {0} passed to the resource adapter did not implement the expected interface {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter dispatch target received a request object that was not of the expected type.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0650E" severity="E" prefix="yes">
  <MsgText pgmKey="XARESOURCE_EXCEPTION_CWSIV0650" varFormat="Java">
    XARESOURCE_EXCEPTION_CWSIV0650=CWSIV0650E: An internal error occurred. The exception {0} was received when attempting to obtain the XAResource from connection {1}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to obtain the XAResource from a connection in order to pass it on endpoint creation.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0155E" severity="E" prefix="yes">
  <MsgText pgmKey="REASSOCIATION_FAILED_CWSIV0155" varFormat="Java">
    REASSOCIATION_FAILED_CWSIV0155=CWSIV0155E: An internal error occurred. The exception {0} was thrown while attempting to re-associate with a managed connection.
  </MsgText>
  <Explanation>
    The current connection has been dissociated from its managed connection and the exception was received while attempting to re-associate.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0779I" severity="I" prefix="yes">
  <MsgText pgmKey="ME_DESTROYED_CWSIV0779" varFormat="Java">
    ME_DESTROYED_CWSIV0779=CWSIV0779I: The last local messaging engine {0} for bus {1} has been destroyed.
  </MsgText>
  <Explanation>
    The given endpoint activation was connecting locally, but no remaining local messaging engines are enabled.  The resource adapter is attempting to connect to a remote messaging engine.
  </Explanation>
  <UserResponse>
    No action is required.
  </UserResponse>
</Message>
<Message ID="CWSIV0158E" severity="E" prefix="yes">
  <MsgText pgmKey="ACTIVE_LOCAL_TRAN_CWSIV0158" varFormat="Java">
    ACTIVE_LOCAL_TRAN_CWSIV0158=CWSIV0158E: There is an active SIUncoordinatedTransaction associated with this connection.
  </MsgText>
  <Explanation>
    An attempt has been made to use a transaction parameter of null when there is still an active SIUncoordinatedTransaction associated with this connection.
  </Explanation>
  <UserResponse>
    Either pass the active SIUncoordinatedTransaction as the transaction parameter, or call commit/rollback on it first before passing null.
  </UserResponse>
</Message>
<Message ID="CWSIV0788I" severity="I" prefix="yes">
  <MsgText pgmKey="CONNECTION_FAILED_CWSIV0788" varFormat="Java">
    CONNECTION_FAILED_CWSIV0788=CWSIV0788I: Failed to create a connection to a messaging engine. The target bus was {0}
  </MsgText>
  <Explanation>
    The system failed to connect to a messaging engine. This may be a temporary connection problem if no messaging engine is available in the bus or this may be a configuration issue with the activation specification being used.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically. If the messaging engine is available then check the activation config settings are correct, particularly the busname.
  </UserResponse>
</Message>
<Message ID="CWSIV0150E" severity="E" prefix="yes">
  <MsgText pgmKey="ACTIVE_LOCAL_TRAN_CWSIV0150" varFormat="Java">
    ACTIVE_LOCAL_TRAN_CWSIV0150=CWSIV0150E: An existing SIUncoordinatedTransaction has not been completed.
  </MsgText>
  <Explanation>
    An attempt has been made to create a new SIUncoordinatedTransaction when the current one has not been completed.
  </Explanation>
  <UserResponse>
    Ensure commit or rollback is called on the current SIUncoordinatedTransaction before creating a new one.
  </UserResponse>
</Message>
<Message ID="CWSIV0905W" severity="W" prefix="yes">
  <MsgText pgmKey="MULTIPLE_MBEAN_EXCEPTION_CWSIV0905" varFormat="Java">
    MULTIPLE_MBEAN_EXCEPTION_CWSIV0905=CWSIV0905W: During an attempt to stop an MDB there were multiple Message Endpoint that were found endpoint {0} which was listening to the destination {1}. Only one endpoint should exist. The MDB will not be stopped.
  </MsgText>
  <Explanation>
    The system detected multiple message endpoints. It was unable to identify which message endpoint to pause.
  </Explanation>
  <UserResponse>
    Check the status of all the message endpoints on this message-driven bean using wsadmin scripting or the administrative console. If a message endpoint is active, pause the endpoint and investigate possible problems with the message-driven bean. Resume the endpoint when you are ready.
  </UserResponse>
</Message>
<Message ID="CWSIV0401E" severity="E" prefix="yes">
  <MsgText pgmKey="UNRECOGNISED_REQUEST_INFO_CWSIV0401" varFormat="Java">
    UNRECOGNISED_REQUEST_INFO_CWSIV0401=CWSIV0401E: An internal error occurred. The connection request information object {0} was not of the expected type {1}.
  </MsgText>
  <Explanation>
    The object passed as the connection request information parameter was not of the expected type.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0402E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_CLOSE_CWSIV0402" varFormat="Java">
    CONNECTION_CLOSE_CWSIV0402=CWSIV0402E: An internal error occurred. The exception {0} was thrown while attempting to close a connection to the messaging engine.
  </MsgText>
  <Explanation>
    An exception was created while attempting to close a connection to the messaging engine.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0502E" severity="E" prefix="yes">
  <MsgText pgmKey="DEST_FACTORY_CWSIV0502" varFormat="Java">
    DEST_FACTORY_CWSIV0502=CWSIV0502E: An internal error.  The following exception was thrown while attempting to obtain an SIDestinationAddressFactory: {0}.
  </MsgText>
  <Explanation>
    During endpoint activation the core SPI resource adapter was attempting to obtain an SIDestinationAddressFactory and an unexpected exception was received.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0789I" severity="I" prefix="yes">
  <MsgText pgmKey="DURSUB_CONNECTION_FAILED_CWSIV0789" varFormat="Java">
    DURSUB_CONNECTION_FAILED_CWSIV0789=CWSIV0789I: Failed to create a connection to a messaging engine that hosts the durable subscription. The target bus was {0} and the durable subscrption home was {1}
  </MsgText>
  <Explanation>
    The system failed to connect to the messaging engine that hosts the durable subscription home. This may be a temporary connection problem if the messaging engine is unavailable in the bus or this may be a configuration issue with the activation specification being used.
  </Explanation>
  <UserResponse>
    Ensure that the messaging engine that host the durable subscription home on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically. If the messaging engine is available then check the activation config settings are correct, particularly the busname and durable subscription home
  </UserResponse>
</Message>
<Message ID="CWSIV1051E" severity="E" prefix="yes">
  <MsgText pgmKey="READ_SET_CWSIV1051" varFormat="Java">
    READ_SET_CWSIV1051=CWSIV1051E: An internal error occurred. The array of messages {3} returned for the message handle {2} from the session {0} on messaging engine {1} did not contain a single message.
  </MsgText>
  <Explanation>
    The inbound resource adapter dispatch target did not receive back a single message in exchange for the given message handle.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0784I" severity="I" prefix="yes">
  <MsgText pgmKey="ME_STOPPING_CWSIV0784" varFormat="Java">
    ME_STOPPING_CWSIV0784=CWSIV0784I: The local messaging engine {0} on bus {1} is stopping.
  </MsgText>
  <Explanation>
    The given endpoint activation was using a messaging engine that has now been stopped. The resource adapter will attempt to connect to a different messaging engine.
  </Explanation>
  <UserResponse>
    No action is required.
  </UserResponse>
</Message>
<Message ID="CWSIV0764I" severity="I" prefix="yes">
  <MsgText pgmKey="NEW_CONSUMER_CWSIV0764" varFormat="Java">
    NEW_CONSUMER_CWSIV0764=CWSIV0764I: A consumer has been created for a message-driven bean against destination {2} on bus {0} following the activation of messaging engine {1}.
  </MsgText>
  <Explanation>
    The activation of a messaging engine on the required bus has led to the creation of a new consumer for the given destination.
  </Explanation>
  <UserResponse>
    No action is required.
  </UserResponse>
</Message>
<Message ID="CWSIV0351E" severity="E" prefix="yes">
  <MsgText pgmKey="NON_MANAGED_ENVIRONMENT_CWSIV0351" varFormat="Java">
    NON_MANAGED_ENVIRONMENT_CWSIV0351=CWSIV0351E: Creation of a connection factory in a non-managed environment is not supported.
  </MsgText>
  <Explanation>
    The creation of a connection factory is not supported in a non-managed environment when using the RA_CONNECTION implementation of the core SPI because a connection manager is required to provide container transaction support.
  </Explanation>
  <UserResponse>
    In a non-managed environment create a connection factory using the SICoreConnectionFactorySelector with a FactoryType other than RA_CONNECTION.
  </UserResponse>
</Message>
<Message ID="CWSIV0511E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_MAXCONC_CWSIV0511" varFormat="Java">
    INVALID_PROPERTY_MAXCONC_CWSIV0511=CWSIV0511E: The maximum concurrency on a Core SPI activation specification must be given a positive value
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the maximum concurrency was found not to be valid.
  </Explanation>
  <UserResponse>
    Correct the value of the maximum concurrency property on the activation specification then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV1203E" severity="E" prefix="yes">
  <MsgText pgmKey="SYNC_CWSIV1203" varFormat="Java">
    SYNC_CWSIV1203=CWSIV1203E: The transaction {0} returned from the connection did not implement the expected interface {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter requires the uncoordinated transaction to implement the given interface in order to perform the one-phase commit optimization.
  </Explanation>
  <UserResponse>
    Ensure that the system is correctly configured in order to take advantage of the one-phase commit optimization between a messaging engine and a database when also using entity beans that use container managed persistence.
  </UserResponse>
</Message>
<Message ID="CWSIV1154W" severity="W" prefix="yes">
  <MsgText pgmKey="INVALID_MESSAGELOCKEXPIRY_CWSIV1154" varFormat="Java">
    INVALID_MESSAGELOCKEXPIRY_CWSIV1154=CWSIV1154W: The value for the MessageLockExpiry appears to be {0}, this can not be converted to an integer. The default value of {1} will be used.
  </MsgText>
  <Explanation>
    When reading the value for MessageLockExpiry it was unable to convert the value to an integer.
  </Explanation>
  <UserResponse>
    Check the value assigned to the custom property MessageLockExpiry is an integer, restart the server for the changes to take effect.
  </UserResponse>
</Message>
<Message ID="CWSIV0765E" severity="E" prefix="yes">
  <MsgText pgmKey="MESSAGING_ENGINE_STOPPING_CWSIV0765" varFormat="Java">
    MESSAGING_ENGINE_STOPPING_CWSIV0765=CWSIV0765E: The exception {0} was thrown when attempting to create a connection to another messaging engine during the stopping of messaging engine {1} on bus {2}.
  </MsgText>
  <Explanation>
    During the stopping of the given messaging engine the resource adapter received an exception when attempting to connect to an alternative messaging engine.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.  After resolving issue, restart messaging engine or resource adapter.
  </UserResponse>
</Message>
<Message ID="CWSIV0354E" severity="E" prefix="yes">
  <MsgText pgmKey="UNRECOGNISED_REQUEST_INFO_CWSIV0354" varFormat="Java">
    UNRECOGNISED_REQUEST_INFO_CWSIV0354=CWSIV0354E: An internal error occurred. The connection request information object {0} was not of the expected type {1}.
  </MsgText>
  <Explanation>
    The object passed as the connection request information parameter was not of the expected type.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0608E" severity="E" prefix="yes">
  <MsgText pgmKey="DELETE_EXCEPTION_CWSIV0608" varFormat="Java">
    DELETE_EXCEPTION_CWSIV0608=CWSIV0608E: An internal error occurred. When attempting to delete the message handle {1} under transaction {2}, the following exception was thrown {0}
  </MsgText>
  <Explanation>
    The resource adapter encountered a problem while attempting to delete a message handle
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0602E" severity="E" prefix="yes">
  <MsgText pgmKey="DELETE_EXCEPTION_CWSIV0602" varFormat="Java">
    DELETE_EXCEPTION_CWSIV0602=CWSIV0602E: An internal error occurred. The exception {0} was received when attempting to delete the message {1} under transaction {2}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to delete a message under the given transaction.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0508E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_DESTINATION_TYPE_CWSIV0508" varFormat="Java">
    INVALID_PROPERTY_DESTINATION_TYPE_CWSIV0508=CWSIV0508E: The following destination type on a Core SPI activation specification is invalid [{3}]. The values [{0}] or [{1}] or [{2}] are expected.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the destination type was found not to be valid. Since no destination name is supplied Topics are not permitted
  </Explanation>
  <UserResponse>
    Correct the value of the destination type property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0759W" severity="W" prefix="yes">
  <MsgText pgmKey="NO_ACTIVE_MES_CWSIV0759" varFormat="Java">
    NO_ACTIVE_MES_CWSIV0759=CWSIV0759W: During activation of a message-driven bean, no suitable active messaging engines were found in the local server on the bus {0}.
  </MsgText>
  <Explanation>
    A message-driven bean was configured to connect to the given bus but there are no suitable active messaging engines within the local server.  Message consumption will begin when a suitable local messaging engine becomes active.
  </Explanation>
  <UserResponse>
    Ensure that a suitable messaging engine is started. A message is displayed when a successful connection is made.
  </UserResponse>
</Message>
<Message ID="CWSIV0907W" severity="W" prefix="yes">
  <MsgText pgmKey="MAXSEQUENTIALMESSAGEFAILURE_EXCEPTION_DESTINATION_CWSIV0907" varFormat="Java">
    MAXSEQUENTIALMESSAGEFAILURE_EXCEPTION_DESTINATION_CWSIV0907=CWSIV0907W: The MDB maximum sequential message failure configuration value has been changed from the value {0} to {1}.
  </MsgText>
  <Explanation>
    The maximum sequential message failure value has changed because no exception destination is defined for the destination on which the message-driven bean is listening.
  </Explanation>
  <UserResponse>
    No action is necessary unless you require the sequential message failure function. If you require the sequential message failure function, configure an exception destination for the destination.
  </UserResponse>
</Message>
<Message ID="CWSIV0774W" severity="W" prefix="yes">
  <MsgText pgmKey="FAILURE_DURING_RELOAD_CWSIV0774" varFormat="Java">
    FAILURE_DURING_RELOAD_CWSIV0774=CWSIV0774W: The exception {0} was thrown to the consumer for destination {1} on messaging engine {2} on bus {3} for endpoint activation {4} while the messaging engine was reloading its configuration.
  </MsgText>
  <Explanation>
    The given exception was received for a consumer while the corresponding messaging engine was reloading its configuration.
  </Explanation>
  <UserResponse>
    This warning can be ignored if the queue point to which the consumer was attached has deliberately been deleted as part of the configuration updates. If a replacement queue point has been defined, then a new consumer will be created when the update has completed.
  </UserResponse>
</Message>
<Message ID="CWSIV0505E" severity="E" prefix="yes">
  <MsgText pgmKey="INVALID_PROPERTY_DESTINATION_TYPE_CWSIV0505" varFormat="Java">
    INVALID_PROPERTY_DESTINATION_TYPE_CWSIV0505=CWSIV0505E: The following destination type on a Core SPI activation specification is invalid [{4}]. The values [{0}] or [{1}] or [{2}] or [{3}] are expected.
  </MsgText>
  <Explanation>
    During validation of the properties configured on a Core SPI activation specification the destination type was found not to be valid.
  </Explanation>
  <UserResponse>
    Correct the value of the destination type property on the activation specification, then restart the server.
  </UserResponse>
</Message>
<Message ID="CWSIV0001W" severity="W" prefix="yes">
  <MsgText pgmKey="RECOVERY_ALIAS_NOT_RESOLVED_CWSIV0001" varFormat="Java">
    RECOVERY_ALIAS_NOT_RESOLVED_CWSIV0001=CWSIV0001W: Failed to resolve the security alias {0} during recovery processing.
  </MsgText>
  <Explanation>
    A security alias was specified on the resource for which recovery processing is taking place and could not be resolved.  Processing will continue with a null user name and password.
  </Explanation>
  <UserResponse>
    Ensure that the specified alias is defined for the application server in which recovery processing is taking place.
  </UserResponse>
</Message>
<Message ID="CWSIV0407E" severity="E" prefix="yes">
  <MsgText pgmKey="LOCAL_TRAN_ROLLBACK_CWSIV0407" varFormat="Java">
    LOCAL_TRAN_ROLLBACK_CWSIV0407=CWSIV0407E: An internal error occurred. The exception {0} was thrown while the container was attempting to roll back a local transaction.
  </MsgText>
  <Explanation>
    An exception was created while the container was attempting to roll back a local transaction.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0809W" severity="W" prefix="yes">
  <MsgText pgmKey="NO_LISTENERS_CREATED_CWSIV0809" varFormat="Java">
    NO_LISTENERS_CREATED_CWSIV0809=CWSIV0809W: The wildcard destination name {0} matched zero destinations that are available for consumption of messages on messaging engine {1} on bus {2}
  </MsgText>
  <Explanation>
    The activation specification contains a wildcard destination name in order to consume messages from multiple destinations, however the wildcard name matches zero available destinations
  </Explanation>
  <UserResponse>
    Ensure that the activation specification should be using wildcarding destination name, that the destination wildcarded name will match some destinations and that the specifed user details are allowed to consume from the destinations.
  </UserResponse>
</Message>
<Message ID="CWSIV1210E" severity="E" prefix="yes">
  <MsgText pgmKey="NULL_XA_RESOURCE_CWSIV1210" varFormat="Java">
    NULL_XA_RESOURCE_CWSIV1210=CWSIV1210E: An internal error occured, a null was passed in to the method {1} on object {0}. A valid XAResource must be passed in.
  </MsgText>
  <Explanation>
    This exception is unexpected. The cause is not immediately known.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0769W" severity="W" prefix="yes">
  <MsgText pgmKey="ATTACH_FAILED_CWSIV0769" varFormat="Java">
    ATTACH_FAILED_CWSIV0769=CWSIV0769W: The creation of a consumer for remote destination {0} on bus {1} for endpoint activation {2} failed with exception {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter successfully connected to a local messaging engine but then received an exception when attempting to create a consumer on a remote queue point.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine with a queue point for the given destination is available.  The resource adapter will automatically re-attempt the creation of the consumer periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV1052W" severity="W" prefix="yes">
  <MsgText pgmKey="EXCEPTION_CWSIV1052" varFormat="Java">
    EXCEPTION_CWSIV1052=CWSIV1052W: The inbound resource adapter received the exception {3} when processing the message handle {2} from the session {0} on messaging engine {1}.
  </MsgText>
  <Explanation>
    The inbound resource adapter was unable to process the given message handle received from the control region adjunct.
  </Explanation>
  <UserResponse>
    See exception details for cause.  Message delivery will be reattempted once the message lock has expired.
  </UserResponse>
</Message>
<Message ID="CWSIV0300E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECTION_CREATION_CWSIV0300" varFormat="Java">
    CONNECTION_CREATION_CWSIV0300=CWSIV0300E: An internal error occurred. The exception {0} was thrown while attempting to create a connection to the messaging engine.
  </MsgText>
  <Explanation>
    An exception was received while attempting to create a connection to the messaging engine.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0754E" severity="E" prefix="yes">
  <MsgText pgmKey="FOREIGN_DESTINATION_CWSIV0754" varFormat="Java">
    FOREIGN_DESTINATION_CWSIV0754=CWSIV0754E: The destination {0} on bus {1} is not defined as a queue point on the bus to which the message-driven bean is connected
  </MsgText>
  <Explanation>
    A message-driven bean must be connected to the bus that hosts the destination from which the bean consumes.  Foreign buses are not supported.
  </Explanation>
  <UserResponse>
    Modify the activation specification for the message-driven bean so that it connects to the required bus or move the destination to the bus to which the message-driven bean is connecting.
  </UserResponse>
</Message>
<Message ID="CWSIV0783E" severity="E" prefix="yes">
  <MsgText pgmKey="CONNECT_FAILED_CWSIV0783" varFormat="Java">
    CONNECT_FAILED_CWSIV0783=CWSIV0783E: The creation of a connection for destination {0} on bus {1} for endpoint activation {2} failed with exception {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter received an exception when attempting to connect to a messaging engine.  The corresponding message-driven bean is deactivating and cannot receive further messages.
  </Explanation>
  <UserResponse>
    See the exception to determine the cause.  After resolving the issue, restart the resource adapter or application.
  </UserResponse>
</Message>
<Message ID="CWSIV0782W" severity="W" prefix="yes">
  <MsgText pgmKey="CONNECT_FAILED_CWSIV0782" varFormat="Java">
    CONNECT_FAILED_CWSIV0782=CWSIV0782W: The creation of a connection for destination {0} on bus {1} for endpoint activation {2} failed with exception {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter received an exception when connecting to a messaging engine.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.
  </UserResponse>
</Message>
<Message ID="CWSIV0406E" severity="E" prefix="yes">
  <MsgText pgmKey="LOCAL_TRAN_COMMIT_CWSIV0406" varFormat="Java">
    LOCAL_TRAN_COMMIT_CWSIV0406=CWSIV0406E: An internal error occurred. The exception {0} was thrown while the container was attempting to commit a local transaction.
  </MsgText>
  <Explanation>
    An exception was created while the container was attempting to commit a local transaction.
  </Explanation>
  <UserResponse>
    See the linked exception for further information.
  </UserResponse>
</Message>
<Message ID="CWSIV0356W" severity="W" prefix="yes">
  <MsgText pgmKey="CONNECTION_ERROR_RETRY_CWSIV0356" varFormat="Java">
    CONNECTION_ERROR_RETRY_CWSIV0356=CWSIV0356W: The following JCA Connection error has occurred when trying to get the connection. The retrieving of the connection will be retried. The exception is {0}.
  </MsgText>
  <Explanation>
    An error has been caught whilst obtaining a connection. The system will purge the connection then attempt to obtain another one.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0603E" severity="E" prefix="yes">
  <MsgText pgmKey="DELETE_SET_EXCEPTION_CWSIV0603" varFormat="Java">
    DELETE_SET_EXCEPTION_CWSIV0603=CWSIV0603E: An internal error occurred. The exception {0} was received when attempting to delete the messages {1} under transaction {2}.
  </MsgText>
  <Explanation>
    The resource adapter received an exception when attempting to delete messages under the given transaction.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="CWSIV0054E" severity="E" prefix="yes">
  <MsgText pgmKey="ALIAS_REQUIRED_CWSIV0054" varFormat="Java">
    ALIAS_REQUIRED_CWSIV0054=CWSIV0054E: Connection factory properties must contain a value for CONTAINER_AUTHENTICATION_ALIAS.
  </MsgText>
  <Explanation>
    The property map passed to the getConnectionFactory method on SICoreConnectionFactorySelector requested that the container provide credentials using the default principal mapping but did not specify a container authentication alias.
  </Explanation>
  <UserResponse>
    Ensure that the set of properties passed to the getConnectionFactory method on SICoreConnectionFactorySelector contains a value for CONTAINER_AUTHENTICATION_ALIAS.
  </UserResponse>
</Message>
<Message ID="CWSIV0775W" severity="W" prefix="yes">
  <MsgText pgmKey="CONNECT_FAILED_CWSIV0775" varFormat="Java">
    CONNECT_FAILED_CWSIV0775=CWSIV0775W: The creation of a connection for destination {0} on bus {1} for endpoint activation {2} failed with exception {3}.
  </MsgText>
  <Explanation>
    The inbound resource adapter received an exception when attempting to connect to a remote messaging engine.
  </Explanation>
  <UserResponse>
    Ensure that a messaging engine on the given bus is available.  The resource adapter automatically attempts to connect to the bus periodically.
  </UserResponse>
</Message>
<Message ID="CWSIV0250E" severity="E" prefix="yes">
  <MsgText pgmKey="ASYNCHRONOUS_METHOD_CWSIV0250" varFormat="Java">
    ASYNCHRONOUS_METHOD_CWSIV0250=CWSIV0250E: Methods relating to asynchronous message receipt are not supported.
  </MsgText>
  <Explanation>
    The use of ConsumerSession methods relating to the asynchronous receipt of messages are not supported when using the RA_CONNECTION implementation of the Platform Messaging core SPI.
  </Explanation>
  <UserResponse>
    If asynchronous receipt of messages is required, use a different implementation of the Platform Messaging core SPI.
  </UserResponse>
</Message>
<!-- END MESSAGES -->
</TMSSource>
