<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../../resources/stylesheets/wasmsgxml.css"?>
<TMSSource name="TivoliMessages" tmsVersion="1.0" xml:lang="en">
<!-- CMVC MSG File Name = ws/code/webcontainer/src/com/ibm/ws/webcontainer/resources/Messages.nlsprops -->
<!-- DO NOT EDIT THIS FILE - This file was generated by the XML/Html & Property emitter -->
<!-- BEGIN MESSAGES -->
<Message ID="SRVE8071E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.webcontainer.config.object" varFormat="Java">
    Null.webcontainer.config.object=SRVE8071E: Null web container config object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0109E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Invalid.ObjectPool.Instantiated." varFormat="Java">
    Illegal.Argument:.Invalid.ObjectPool.Instantiated.=SRVE0109E: Illegal Argument Exception: Invalid ObjectPool instantiated.
  </MsgText>
  <Explanation>
    This is an internal system error and is probably caused by an earlier failure.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE0221E" severity="E" prefix="yes">
  <MsgText pgmKey="Serving.JSP.Not.Allowed" varFormat="Java">
    Serving.JSP.Not.Allowed=SRVE0221E: Serving contents of JSP files is not allowed.
  </MsgText>
  <Explanation>
    Cannot serve the contents of a JSP file
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8078E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.servlet.config.object" varFormat="Java">
    Null.servlet.config.object=SRVE8078E: Null servlet config object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8101E" severity="E" prefix="yes">
  <MsgText pgmKey="Response.buffer.corruption.detected" varFormat="Java">
    Response.buffer.corruption.detected=SRVE8101E: Response buffer corruption detected. Expected remaining={0}, actual={1}.
  </MsgText>
  <Explanation>
    An unexpected internal error has caused a mismatch between the expected state of the output buffer and the actual state.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0162I" severity="I" prefix="yes">
  <MsgText pgmKey="web.container.servlet.spec.level" varFormat="Java">
    web.container.servlet.spec.level=SRVE0162I: Servlet Specification Level: 3.0
  </MsgText>
  <Explanation>
    The servlet specification level supported by the application server.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0245I" severity="I" prefix="yes">
  <MsgText pgmKey="reaper.removing.mapping.[{0}].for.servlet.[{1}]" varFormat="Java">
    reaper.removing.mapping.[{0}].for.servlet.[{1}]=SRVE0245I: Reaper thread removing mapping: [{0}] for servlet: [{0}].
  </MsgText>
  <Explanation>
    The reaper thread removes the mappings for jsps and other extensions that have been inactive longer the the reaper inactive limit.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8060E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.while.injecting.resource" varFormat="Java">
    exception.while.injecting.resource=SRVE8060E: An unexpected exception occurred during resource injection.
  </MsgText>
  <Explanation>
    An unexpected exception occurred during resource injection.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0138E" severity="E" prefix="yes">
  <MsgText pgmKey="postInvoke.Security.Exception." varFormat="Java">
    postInvoke.Security.Exception.=SRVE0138E: postInvoke Security Exception
  </MsgText>
  <Explanation>
    A security problem was encountered during request processing.
  </Explanation>
  <UserResponse>
    Examine the server logs to determine the root cause of the problem.
  </UserResponse>
</Message>
<Message ID="SRVE0208E" severity="E" prefix="yes">
  <MsgText pgmKey="Unsupported.conversion" varFormat="Java">
    Unsupported.conversion=SRVE0208E: Unsupported conversion
  </MsgText>
  <Explanation>
    The code tried to do an illegal conversion of a header value. eg., from int to Data, when such a conversion is not possible. This is an application error.
  </Explanation>
  <UserResponse>
    Modify the failing servlet/JSP.
  </UserResponse>
</Message>
<Message ID="SRVE0287E" severity="E" prefix="yes">
  <MsgText pgmKey="server.root.is.null" varFormat="Java">
    server.root.is.null=SRVE0287E: server.root is null
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8113W" severity="W" prefix="yes">
  <MsgText pgmKey="AsyncContext.lock.already.held" varFormat="Java">
    AsyncContext.lock.already.held=SRVE8113W: Unable to obtain a lock.  Error processing has already been invoked by another thread.
  </MsgText>
  <Explanation>
    Error processing has already been invoked by another thread.
  </Explanation>
  <UserResponse>
    Make sure the application can handle an exception here.  If it is necessary that this method return even if the call doesn&apos;t succeed, contact IBM support.
  </UserResponse>
</Message>
<Message ID="SRVE0297E" severity="E" prefix="yes">
  <MsgText pgmKey="WebApp.destroy.encountered.errors" varFormat="Java">
    WebApp.destroy.encountered.errors=SRVE0297E: Web Application {0} destroy encountered errors: {1}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0311E" severity="E" prefix="yes">
  <MsgText pgmKey="transport.error" varFormat="Java">
    transport.error=SRVE0311E: There was an error in the transport: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0016E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Invalid.Header.Format" varFormat="Java">
    Illegal.Argument:.Invalid.Header.Format=SRVE0016E: Illegal Argument Exception: Invalid header format
  </MsgText>
  <Explanation>
    Format found for a request header is not valid.
  </Explanation>
  <UserResponse>
    Check client header creation.
  </UserResponse>
</Message>
<Message ID="SRVE8027E" severity="E" prefix="yes">
  <MsgText pgmKey="an.io.related.error.has.occurred.during.the.processing.of.the.given.AsyncEvent" varFormat="Java">
    an.io.related.error.has.occurred.during.the.processing.of.the.given.AsyncEvent=SRVE8027E: An I/O related error has occurred during the processing of the given AsyncEvent.
  </MsgText>
  <Explanation>
    I/O errors can occur when invoking an AsyncListener if it is writing to the response concurrently with another thread or something else has closed the response.
  </Explanation>
  <UserResponse>
    It is recommended that AsyncListeners should only call complete or dispatch, but not write to the response. Otherwise, the customer is responsible for doing their own synchronization to prevent an IOException.
  </UserResponse>
</Message>
<Message ID="SRVE8018E" severity="E" prefix="yes">
  <MsgText pgmKey="error.validate.webServlet.zero.mappings" varFormat="Java">
    error.validate.webServlet.zero.mappings=SRVE8018E: The class, {0}, did not have any patterns specified in the annotation
  </MsgText>
  <Explanation>
    The class must specify patterns in the annotation via the urlPatterns or value attribute
  </Explanation>
  <UserResponse>
    Modify the class to add one of the urlPatterns or value attributes
  </UserResponse>
</Message>
<Message ID="SRVE0292I" severity="I" prefix="yes">
  <MsgText pgmKey="log.servlet.message" varFormat="Java">
    log.servlet.message=SRVE0292I: Servlet Message - [{0}]:.{1}
  </MsgText>
  <Explanation>
    Informational message logged for a servlet by use of the ServletContext.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0242I" severity="I" prefix="yes">
  <MsgText pgmKey="[{0}].Initialization.successful" varFormat="Java">
    [{0}].Initialization.successful=SRVE0242I: [{2}] [{1}] [{0}]: Initialization successful.
  </MsgText>
  <Explanation>
    The init() method of the target resource ran successfully and the target has been places into service.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8102E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.value.for.ResponseBuffer" varFormat="Java">
    Illegal.value.for.ResponseBuffer=SRVE8102E: Illegal value for responsebuffersize custom property [{0}].
  </MsgText>
  <Explanation>
    Illegal value for responsebuffersize custom property.
  </Explanation>
  <UserResponse>
    Check the value of the responsebuffersize custom property.
  </UserResponse>
</Message>
<Message ID="SRVE0249W" severity="W" prefix="yes">
  <MsgText pgmKey="sync.tothread.not.set.for.server.[{0}]" varFormat="Java">
    sync.tothread.not.set.for.server.[{0}]=SRVE0249W: Application {0} has requested SyncToOSThread, but the server is not enabled for SyncToOSThread
  </MsgText>
  <Explanation>
    SyncToOSThread synchronizes the Java EE role identity to the OS thread, meaning that the OS thread identity is made equal to the Java EE role identity for the duration of the request. This message indicates that while an application has been configured to utilize SyncToOSThread functionality, the server it is installed into is not configured to support SyncToOSThread capabilities. System action is required.
  </Explanation>
  <UserResponse>
    If SyncToOSThread capabilities are desired for the server in question, refer to the information center for a description as to how to enable SyncToOSThread for a server.
  </UserResponse>
</Message>
<Message ID="SRVE8045E" severity="E" prefix="yes">
  <MsgText pgmKey="programmatic.sessions.disabled" varFormat="Java">
    programmatic.sessions.disabled=SRVE8045E: Programmatic session configuration has been disabled on this server.
  </MsgText>
  <Explanation>
    Programmatic session configuration has been disabled on this server.
  </Explanation>
  <UserResponse>
    Enable programmatic session configuration.
  </UserResponse>
</Message>
<Message ID="SRVE0270E" severity="E" prefix="yes">
  <MsgText pgmKey="illegal.servlet.mapping" varFormat="Java">
    illegal.servlet.mapping=SRVE0270E: Illegal servlet mapping encountered for servlet {0}.
  </MsgText>
  <Explanation>
    A servlet mapping specified in the webconfig.xml is not valid. System action is required.
  </Explanation>
  <UserResponse>
    Check the servlet mappings in webconfig.xml and make appropriate changes
  </UserResponse>
</Message>
<Message ID="SRVE8061E" severity="E" prefix="yes">
  <MsgText pgmKey="unable.to.invoke.method" varFormat="Java">
    unable.to.invoke.method=SRVE8061E: Unable to invoke method --&gt; [{0}] on class --&gt; [{1}].
  </MsgText>
  <Explanation>
    Problem invoking postConstruct or preDestroy.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0133E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.Parsing.Parameters" varFormat="Java">
    Error.Parsing.Parameters=SRVE0133E: An error occurred while parsing parameters. {0}
  </MsgText>
  <Explanation>
    Problem encountered parsing servlet parameters.
  </Explanation>
  <UserResponse>
    Verify the client is sending the full request.
  </UserResponse>
</Message>
<Message ID="SRVE0100E" severity="E" prefix="yes">
  <MsgText pgmKey="Uncaught.init().exception.thrown.by.servlet.{0}:.{2}" varFormat="Java">
    Uncaught.init().exception.thrown.by.servlet.{0}:.{2}=SRVE0100E: Uncaught init() exception created by servlet {0} in application {1}: {2}
  </MsgText>
  <Explanation>
    Could not initialize the specified servlet. This is an application error.
  </Explanation>
  <UserResponse>
    Make sure the servlet class file is available on the application class path.
  </UserResponse>
</Message>
<Message ID="SRVE8105W" severity="W" prefix="yes">
  <MsgText pgmKey="unable.to.retrieve.timer.manager" varFormat="Java">
    unable.to.retrieve.timer.manager=SRVE8105W: An error occurred retrieving the timer manager to kick of async servlet timeouts. Using default single-threaded timer.
  </MsgText>
  <Explanation>
    The administrative console should not allow you to pick an invalid timer manager JNDI name.
  </Explanation>
  <UserResponse>
    Verify the timer manager selected in the web container panel is valid.
  </UserResponse>
</Message>
<Message ID="SRVE8016E" severity="E" prefix="yes">
  <MsgText pgmKey="error.validate.annotation.extension.class" varFormat="Java">
    error.validate.annotation.extension.class=SRVE8016E: The {0} annotation can not be applied to the class, {1}, because it extends the wrong super class
  </MsgText>
  <Explanation>
    Some annotations can only be applied to classes which extend the correct type.
  </Explanation>
  <UserResponse>
    Modify the class to extend the correct super class
  </UserResponse>
</Message>
<Message ID="SRVE8010E" severity="E" prefix="yes">
  <MsgText pgmKey="request.does.not.support.async.servlet.processing" varFormat="Java">
    request.does.not.support.async.servlet.processing=SRVE8010E: The current request does not support asynchronous servlet processing.
  </MsgText>
  <Explanation>
    One of the servlets or filters in the request does not support asynchronous servlets.
  </Explanation>
  <UserResponse>
    Do not use asynchronous servlets or enable asynchronous processing for all the servlets and filters in the chain by adding the async-supported element to the component definitions.
  </UserResponse>
</Message>
<Message ID="SRVE0254E" severity="E" prefix="yes">
  <MsgText pgmKey="unsupported.request.encoding.[{0}]" varFormat="Java">
    unsupported.request.encoding.[{0}]=SRVE0254E: Failed to set request character encoding: [{0}].
  </MsgText>
  <Explanation>
    Request encoding specified on the request is not valid. This is an application error.
  </Explanation>
  <UserResponse>
    Review logs to determine whether the specified encoding is a valid encoding.
  </UserResponse>
</Message>
<Message ID="SRVE8091W" severity="W" prefix="yes">
  <MsgText pgmKey="servlet.wrapper.unavailable" varFormat="Java">
    servlet.wrapper.unavailable=SRVE8091W: Servlet {0} is currently unavailable: {1}
  </MsgText>
  <Explanation>
    An UnavailableException was thrown from the servlet.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0320E" severity="E" prefix="yes">
  <MsgText pgmKey="Filter.found.but.injection.failure" varFormat="Java">
    Filter.found.but.injection.failure=SRVE0320E: The [{0}] filter was found, but a resource injection failure has occurred.
  </MsgText>
  <Explanation>
    The filter failed to initialize because an error occurred when a resource was injected.
  </Explanation>
  <UserResponse>
    Verify that the injected resources exist and are accessible to the filter.
  </UserResponse>
</Message>
<Message ID="SRVE0315E" severity="E" prefix="yes">
  <MsgText pgmKey="Exception" varFormat="Java">
    Exception=SRVE0315E: An execption occurred: {0}
  </MsgText>
  <Explanation>
    An exception occurred.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0060E" severity="E" prefix="yes">
  <MsgText pgmKey="Unable.to.bind.hostname.[{0}].to.servletHost.[{1}]" varFormat="Java">
    Unable.to.bind.hostname.[{0}].to.servletHost.[{1}]=SRVE0060E: Unable to bind host name [{0}] to servletHost [{1}]
  </MsgText>
  <Explanation>
    Could not bind the specified host name to the specified servlet host.
  </Explanation>
  <UserResponse>
    Make sure the host name has been specified correctly and that the servlet host has been specified in virtualhosts.xml.
  </UserResponse>
</Message>
<Message ID="SRVE0103E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.ScriptName.must.be.the.first.part.of.the.URI" varFormat="Java">
    Illegal.Argument:.ScriptName.must.be.the.first.part.of.the.URI=SRVE0103E: Illegal Argument Exception: ScriptName must be the first part of the URI
  </MsgText>
  <Explanation>
    This is an internal system error and is probably caused by an earlier failure.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE0308E" severity="E" prefix="yes">
  <MsgText pgmKey="filtering.by.asterisk" varFormat="Java">
    filtering.by.asterisk=SRVE0308E: Filtering by asterisk is not allowed.
  </MsgText>
  <Explanation>
    Filtering by asterisk is not allowed because disabling serving all servlets by classname is handled by the com.ibm.ws.webcontainer.disallowserveservletsbyclassname custom property. This is an application error.
  </Explanation>
  <UserResponse>
    Set com.ibm.ws.webcontainer.disallowserveservletsbyclassname to true to block serving all classes by classname.
  </UserResponse>
</Message>
<Message ID="SRVE0294E" severity="E" prefix="yes">
  <MsgText pgmKey="log.servlet.error.and.message" varFormat="Java">
    log.servlet.error.and.message=SRVE0294E: [Servlet Error]-[{0}]: {1}: {2}
  </MsgText>
  <Explanation>
    Error message and exception logged for a servlet for a servlet by use of the ServletContext..
  </Explanation>
  <UserResponse>
    Review the message and exception to determine the cause of the error and the action required. Additional information for may be available in the server logs.
  </UserResponse>
</Message>
<Message ID="SRVE0268E" severity="E" prefix="yes">
  <MsgText pgmKey="error.obtaining.session.context" varFormat="Java">
    error.obtaining.session.context=SRVE0268E: Error obtaining Session Context for the web application: {0}
  </MsgText>
  <Explanation>
    Could not obtain a valid Session Context for the web application. System action is required.
  </Explanation>
  <UserResponse>
    Check if the Session Manager is configured correctly.
  </UserResponse>
</Message>
<Message ID="SRVE0215E" severity="E" prefix="yes">
  <MsgText pgmKey="non-HTTP.request.or.response" varFormat="Java">
    non-HTTP.request.or.response=SRVE0215E: non-HTTP request or response
  </MsgText>
  <Explanation>
    The servlet chain that has been defined can only handle HTTP requests. This is an application error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8054E" severity="E" prefix="yes">
  <MsgText pgmKey="setting.maxIdleTime.to.default.value.of.60000" varFormat="Java">
    setting.maxIdleTime.to.default.value.of.60000=SRVE8054E: A NumberFormatException occurred when trying to set the single thread model servlet maximum idle time.
  </MsgText>
  <Explanation>
    A NumberFormatException occurred when trying to set the single thread model servlet maximum idle time.
  </Explanation>
  <UserResponse>
    Verify the value for the single thread model servlet maximum idle time is a valid integer.
  </UserResponse>
</Message>
<Message ID="SRVE0307W" severity="W" prefix="yes">
  <MsgText pgmKey="Null.Filter.Mapping" varFormat="Java">
    Null.Filter.Mapping=SRVE0307W: null mapping for filter. This may occur if you try to specify a * mapping on a pre-2.5 app.
  </MsgText>
  <Explanation>
    There was no servlet mapping for the filter so it cannot be added. This is an application error.
  </Explanation>
  <UserResponse>
    Change the application descriptors to 2.5 level if you are using a * mapping.
  </UserResponse>
</Message>
<Message ID="SRVE0304E" severity="E" prefix="yes">
  <MsgText pgmKey="servletrequestwrapper.is.not.an.instance.of.so.wrapped.logic.may.be.bypassed" varFormat="Java">
    servletrequestwrapper.is.not.an.instance.of.so.wrapped.logic.may.be.bypassed=SRVE0304E: ServletRequestWrapper [{0}] is not an instance of [{1}] so wrapped logic may be bypassed.
  </MsgText>
  <Explanation>
    Web Container expects a wrapped request object to be an instance of a class of which it is not. This is an application error.
  </Explanation>
  <UserResponse>
    Change code to implement the expected interface.
  </UserResponse>
</Message>
<Message ID="SRVE0086E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Missing.Resource.Bootstrap.Properties" varFormat="Java">
    Illegal.Argument:.Missing.Resource.Bootstrap.Properties=SRVE0086E: Illegal Argument Exception: Missing resource bootstrap properties
  </MsgText>
  <Explanation>
    Internal server error.
  </Explanation>
  <UserResponse>
    Gather logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0288E" severity="E" prefix="yes">
  <MsgText pgmKey="chown.failed" varFormat="Java">
    chown.failed=SRVE0288E: chown failed, tried to run command: [{0}] Exit Code: [{1}]
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8069E" severity="E" prefix="yes">
  <MsgText pgmKey="null.session.registry" varFormat="Java">
    null.session.registry=SRVE8069E: The Session registry is NULL.
  </MsgText>
  <Explanation>
    The Session registry is NULL possibly because the SessionManager did not start up correctly. Web applications WILL fail.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0246I" severity="I" prefix="yes">
  <MsgText pgmKey="reaper.destroying.servlet.[{0}]" varFormat="Java">
    reaper.destroying.servlet.[{0}]=SRVE0246I: Reaper thread destroying servlet: [{0}].
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0194E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.from.included.servlet" varFormat="Java">
    Illegal.from.included.servlet=SRVE0194E: Illegal from included servlet
  </MsgText>
  <Explanation>
    The attempted operation cannot be performed in an included servlet/JSP (Refer to the Servlet specification). This is an application error.
  </Explanation>
  <UserResponse>
    Modify the failing servlet/JSP.
  </UserResponse>
</Message>
<Message ID="SRVE0207E" severity="E" prefix="yes">
  <MsgText pgmKey="Uncaught.initialization.exception.thrown.by.servlet" varFormat="Java">
    Uncaught.initialization.exception.thrown.by.servlet=SRVE0207E: Uncaught initialization exception created by servlet
  </MsgText>
  <Explanation>
    The target threw an exception during initialization that was not caught by the user code. This is an application error.
  </Explanation>
  <UserResponse>
    Account for the exception in target code.
  </UserResponse>
</Message>
<Message ID="SRVE8023E" severity="E" prefix="yes">
  <MsgText pgmKey="multipart.file.upload.exception" varFormat="Java">
    multipart.file.upload.exception=SRVE8023E: There was an exception uploading the file.
  </MsgText>
  <Explanation>
    There was an exception uploading the file.
  </Explanation>
  <UserResponse>
    Investigate nested error and perform appropriate action.
  </UserResponse>
</Message>
<Message ID="SRVE8009E" severity="E" prefix="yes">
  <MsgText pgmKey="error.while.initializing.target.mappings" varFormat="Java">
    error.while.initializing.target.mappings=SRVE8009E: An unexpected internal server error occurred when initializing the target mappings.
  </MsgText>
  <Explanation>
    An unexpected internal server error occurred when initializing the target mappings.
  </Explanation>
  <UserResponse>
    Collect server logs and contact IBM support.
  </UserResponse>
</Message>
<Message ID="SRVE8006E" severity="E" prefix="yes">
  <MsgText pgmKey="add.filter.mapping.to.empty.url.patterns" varFormat="Java">
    add.filter.mapping.to.empty.url.patterns=SRVE8006E: Attempted to add a filter mapping with an empty variable argument url pattern parameter.
  </MsgText>
  <Explanation>
    The variable argument url-pattern parameter passed to FilterRegistration.addMappingForUrlPatterns must be non-null and non-empty.
  </Explanation>
  <UserResponse>
    Modify application code according to error explanation.
  </UserResponse>
</Message>
<Message ID="SRVE0264E" severity="E" prefix="yes">
  <MsgText pgmKey="error.initializing.extension.factories" varFormat="Java">
    error.initializing.extension.factories=SRVE0264E: Error occured while initializing Extension Factories: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0228E" severity="E" prefix="yes">
  <MsgText pgmKey="classname.defined.in.server.using.proper.case.and.fully.qualified.package" varFormat="Java">
    classname.defined.in.server.using.proper.case.and.fully.qualified.package=SRVE0228E: Check that the classname has been defined in the server using the proper case and fully qualified package.
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Check that the classname has been defined in the server using the proper case and fully qualified package.
  </UserResponse>
</Message>
<Message ID="SRVE0310E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.in.WebContainer.custom.property.value" varFormat="Java">
    Error.in.WebContainer.custom.property.value=SRVE0310E: There was an error in a custom property: {1}
  </MsgText>
  <Explanation>
    System action is required.
  </Explanation>
  <UserResponse>
    Verify the custom property is correct
  </UserResponse>
</Message>
<Message ID="SRVE0120E" severity="E" prefix="yes">
  <MsgText pgmKey="IO.Error" varFormat="Java">
    IO.Error=SRVE0120E: IO Error {0}
  </MsgText>
  <Explanation>
    IO error encountered.
  </Explanation>
  <UserResponse>
    Varies depending on reported root cause.
  </UserResponse>
</Message>
<Message ID="SRVE8012E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.adding.ServletContextListener" varFormat="Java">
    Error.adding.ServletContextListener=SRVE8012E: Error adding ServletContextListener
  </MsgText>
  <Explanation>
    A ServletContextListener can not be added from another ServletContextListener
  </Explanation>
  <UserResponse>
    Either add the ServletContextListener to the web.xml or web-fragment.xml, annotate it with the @WebListener annotation, or programmatically add it from ServletContainerInitializer#onStartup
  </UserResponse>
</Message>
<Message ID="SRVE8022E" severity="E" prefix="yes">
  <MsgText pgmKey="multipart.request.size.too.big" varFormat="Java">
    multipart.request.size.too.big=SRVE8022E: The request is too large.
  </MsgText>
  <Explanation>
    The multipart/form-data request is larger than the maximum configured size.
  </Explanation>
  <UserResponse>
    Increase the request size attribute of the multipart configuration for the given servlet.
  </UserResponse>
</Message>
<Message ID="SRVE0213E" severity="E" prefix="yes">
  <MsgText pgmKey="class.not.found" varFormat="Java">
    class.not.found=SRVE0213E: class not found
  </MsgText>
  <Explanation>
    Internal exception.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="SRVE8096W" severity="W" prefix="yes">
  <MsgText pgmKey="exception.scheduling.work.item" varFormat="Java">
    exception.scheduling.work.item=SRVE8096W: An exception occurred scheduling the runnable [{0}].
  </MsgText>
  <Explanation>
    When scheduling a work item with an asynchronous beans work manager, an exception may be thrown if the work queue is full and the configured work queue full action is to fail.
  </Explanation>
  <UserResponse>
    Evaluate whether the work queue full action should be to block until the queue is not full or handle this exception in your application code.
  </UserResponse>
</Message>
<Message ID="SRVE8011E" severity="E" prefix="yes">
  <MsgText pgmKey="Unsupported.op.from.servlet.context.listener" varFormat="Java">
    Unsupported.op.from.servlet.context.listener=SRVE8011E: This operation cannot be executed from a programmatically added listener. (Operation: {0} | Listener: {1} | Application: {2})
  </MsgText>
  <Explanation>
    Certain operations cannot be executed from a programmatically added listener since there is no configuration option to restrict their execution when they are defined in a Tag Library Descriptor (TLD).
  </Explanation>
  <UserResponse>
    Add the listener via an annotation or via the web.xml to enable the execution of this method.
  </UserResponse>
</Message>
<Message ID="SRVE8082E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.while.adding.static.file.processor" varFormat="Java">
    Error.while.adding.static.file.processor=SRVE8082E: An unexpected internal server error occurred while adding the static file processor.
  </MsgText>
  <Explanation>
    An unexpected internal server error occurred while adding the static file processor.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8021E" severity="E" prefix="yes">
  <MsgText pgmKey="multipart.file.size.too.big" varFormat="Java">
    multipart.file.size.too.big=SRVE8021E: The file being uploaded is too large.
  </MsgText>
  <Explanation>
    The file being uploaded via the multipart/form-data request is larger than the maximum configured size.
  </Explanation>
  <UserResponse>
    Increase the file size attribute of the multipart configuration for the given servlet.
  </UserResponse>
</Message>
<Message ID="SRVE0250I" severity="I" prefix="yes">
  <MsgText pgmKey="module.[{0}].successfully.bound.to.virtualhost.[{1}]" varFormat="Java">
    module.[{0}].successfully.bound.to.virtualhost.[{1}]=SRVE0250I: Web Module {0} has been bound to {1}.
  </MsgText>
  <Explanation>
    The specified web module has been associated to the virtualhost mentioned, and can be accessed through any of the host/port combinations for that virtualhost.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0253I" severity="I" prefix="yes">
  <MsgText pgmKey="[{0}].Destroy.successful" varFormat="Java">
    [{0}].Destroy.successful=SRVE0253I: [{2}] [{1}] [{0}]: Destroy successful.
  </MsgText>
  <Explanation>
    The destroy() method of the target resource ran successfully and the target has been removed from service.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8001E" severity="E" prefix="yes">
  <MsgText pgmKey="error.adding.servlet.after.initialization" varFormat="Java">
    error.adding.servlet.after.initialization=SRVE8001E: Attempted to add servlet dynamically after ServletContext initialization.
  </MsgText>
  <Explanation>
    Servlets can only be dynamically added before the ServletContext is initialized.
  </Explanation>
  <UserResponse>
    Move the code calling the current method into a ServletContainerInitalizer&apos;s onStartup or a ServletContextListener&apos;s contextInitialized method.
  </UserResponse>
</Message>
<Message ID="SRVE0042E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument.Invalid.Content.Length" varFormat="Java">
    Illegal.Argument.Invalid.Content.Length=SRVE0042E: Illegal Argument Exception: Invalid content length
  </MsgText>
  <Explanation>
    This is an internal system error and is probably caused by an earlier failure. This is an application error.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE0139E" severity="E" prefix="yes">
  <MsgText pgmKey="preInvoke.Security.Exception." varFormat="Java">
    preInvoke.Security.Exception.=SRVE0139E: Exception in Security preInvoke {0}
  </MsgText>
  <Explanation>
    Security problem encountered during request processing. This is a system error.
  </Explanation>
  <UserResponse>
    Varies with root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0293E" severity="E" prefix="yes">
  <MsgText pgmKey="log.servlet.error" varFormat="Java">
    log.servlet.error=SRVE0293E: [Servlet Error]-[{0}]: {1}
  </MsgText>
  <Explanation>
    Error exception logged for a servlet by use of the ServletContext.
  </Explanation>
  <UserResponse>
    Review the exception to determine the cause of the error and the action required. Additional information for may be available in the server logs.
  </UserResponse>
</Message>
<Message ID="SRVE0275E" severity="E" prefix="yes">
  <MsgText pgmKey="error.adding.servlet.mapping.for.servlet" varFormat="Java">
    error.adding.servlet.mapping.for.servlet=SRVE0275E: Error while adding servlet mapping for servlet [{0}] in application [{1}]: {2}
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Verify the mapping is valid.
  </UserResponse>
</Message>
<Message ID="SRVE0280E" severity="E" prefix="yes">
  <MsgText pgmKey="extension.processor.failed.to.initialize.in.factory" varFormat="Java">
    extension.processor.failed.to.initialize.in.factory=SRVE0280E: Extension processor failed to initialize in factory [{0}]: {1}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8049E" severity="E" prefix="yes">
  <MsgText pgmKey="Exception.occured.during.servlet.destroy" varFormat="Java">
    Exception.occured.during.servlet.destroy=SRVE8049E: An internal server error occurred destroying the servlet.
  </MsgText>
  <Explanation>
    An internal server error occurred destroying the servlet.
  </Explanation>
  <UserResponse>
    See the root cause of the exception.
  </UserResponse>
</Message>
<Message ID="SRVE0243I" severity="I" prefix="yes">
  <MsgText pgmKey="reaper.with.interval.[{0}].limit.[{1}].started" varFormat="Java">
    reaper.with.interval.[{0}].limit.[{1}].started=SRVE0243I: Reaper thread interval: [{0}] and inactive limit:[{1}] started.
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8002E" severity="E" prefix="yes">
  <MsgText pgmKey="error.adding.filter.after.initialization" varFormat="Java">
    error.adding.filter.after.initialization=SRVE8002E: Attempted to add filter dynamically after ServletContext initialization.
  </MsgText>
  <Explanation>
    Filters can only be dynamically added before the ServletContext is initialized.
  </Explanation>
  <UserResponse>
    Move the code calling the current method into a ServletContainerInitalizer&apos;s onStartup or a ServletContextListener&apos;s contextInitialized method.
  </UserResponse>
</Message>
<Message ID="SRVE0181I" severity="I" prefix="yes">
  <MsgText pgmKey="[{0}][{1}][Servlet.LOG]:.{2}:.{3}" varFormat="Java">
    [{0}][{1}][Servlet.LOG]:.{2}:.{3}=SRVE0181I: [{0}] [{1}] [Servlet.LOG]: {2}: {3}
  </MsgText>
  <Explanation>
    Informational message and stack trace logged via ServletContext.log from an application.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8084E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.occurred.while.populating.the.namespace" varFormat="Java">
    Error.occurred.while.populating.the.namespace=SRVE8084E: An unexpected internal server error occurred while populating the namespace. Application name: {0}, Exception : {1}.
  </MsgText>
  <Explanation>
    An unexpected error occurred while populating the namespace.
  </Explanation>
  <UserResponse>
    Check the server logs and exception to determine what might have caused the namespace binding problem.
  </UserResponse>
</Message>
<Message ID="SRVE0031E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.{0}.is.not.a.directory." varFormat="Java">
    Illegal.Argument:.{0}.is.not.a.directory.=SRVE0031E: Illegal Argument Exception: {0} is not a directory.
  </MsgText>
  <Explanation>
    The specified path is not a directory.
  </Explanation>
  <UserResponse>
    Make sure the directory exists or that you are requesting the right directory.
  </UserResponse>
</Message>
<Message ID="SRVE8075E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.cachedServlet.object" varFormat="Java">
    Null.cachedServlet.object=SRVE8075E: Null cache servlet object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8040E" severity="E" prefix="yes">
  <MsgText pgmKey="cannot.call.startAsync.multiple.times.within.same.dispatch" varFormat="Java">
    cannot.call.startAsync.multiple.times.within.same.dispatch=SRVE8040E: Cannot call startAsync multiple times within same dispatch.
  </MsgText>
  <Explanation>
    The method startAsync cannot be called multiple times from the same dispatch. A call to AsyncContext.dispatch would allow you to call startAsync again.
  </Explanation>
  <UserResponse>
    Verify there are no code logic or timing issues causing this illegal behavior.
  </UserResponse>
</Message>
<Message ID="SRVE0247E" severity="E" prefix="yes">
  <MsgText pgmKey="reaper.thread.error" varFormat="Java">
    reaper.thread.error=SRVE0247E: Error during reaper thread execution.
  </MsgText>
  <Explanation>
    Exception occurred in the reaper thread processing. This is a system error.
  </Explanation>
  <UserResponse>
    Reaper processing is just a form of garbage collection.
  </UserResponse>
</Message>
<Message ID="SRVE0301I" severity="I" prefix="yes">
  <MsgText pgmKey="encountered.problems.while.removing.servlet" varFormat="Java">
    encountered.problems.while.removing.servlet=SRVE0301I: Encountered problems while removing servlet {0}. Details: {1}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8029E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.creating.search.path" varFormat="Java">
    exception.creating.search.path=SRVE8029E: An IOException occured creating the Extended Document Root search path.
  </MsgText>
  <Explanation>
    Because creation of the search path involves file system access, IOExceptions may occur.
  </Explanation>
  <UserResponse>
    Verify that the path is correct and there are no hardware issues.
  </UserResponse>
</Message>
<Message ID="SRVE0303E" severity="E" prefix="yes">
  <MsgText pgmKey="servlet.name.for.servlet.mapping.not.found" varFormat="Java">
    servlet.name.for.servlet.mapping.not.found=SRVE0303E: Servlet name for the servlet mapping {0} could not be found.
  </MsgText>
  <Explanation>
    There is no servlet definition for the servlet mapping.
  </Explanation>
  <UserResponse>
    Check your web.xml has a servlet definition for this servlet mapping.
  </UserResponse>
</Message>
<Message ID="SRVE0276E" severity="E" prefix="yes">
  <MsgText pgmKey="error.initializing.servlet" varFormat="Java">
    error.initializing.servlet=SRVE0276E: Error while initializing Servlet [{0}]: {1}
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8072E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.virtual.host.config.object" varFormat="Java">
    Null.virtual.host.config.object=SRVE8072E: Null virtual host config object.
  </MsgText>
  <Explanation>
    An unexpected configuration exception occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0115E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.occurred.while.invoking.error.reporter" varFormat="Java">
    Error.occurred.while.invoking.error.reporter=SRVE0115E: Error occurred while invoking error reporter {0}
  </MsgText>
  <Explanation>
    There was a problem invoking the specified error reporter.
  </Explanation>
  <UserResponse>
    If the problem persists, see problem determination information on the WebSphere Application Server Support page at http://www.ibm.com/software/webservers/appserv/was/support/
  </UserResponse>
</Message>
<Message ID="SRVE8053E" severity="E" prefix="yes">
  <MsgText pgmKey="setting.initialPoolSize.to.default.value.of.5" varFormat="Java">
    setting.initialPoolSize.to.default.value.of.5=SRVE8053E: A NumberFormatException occurred when trying to set the single thread model pool size.
  </MsgText>
  <Explanation>
    A NumberFormatException occurred when trying to set the single thread model pool size.
  </Explanation>
  <UserResponse>
    Verify the value for the single thread model pool size is a valid integer.
  </UserResponse>
</Message>
<Message ID="SRVE8024E" severity="E" prefix="yes">
  <MsgText pgmKey="multipart.request.not.multipart" varFormat="Java">
    multipart.request.not.multipart=SRVE8024E: The request is not of type multipart/form-data.
  </MsgText>
  <Explanation>
    The request must be of type multipart/form-data to be able to handle this method.
  </Explanation>
  <UserResponse>
    Modify the servlets making previous requests such that the current request is of type multipart/form-data.
  </UserResponse>
</Message>
<Message ID="SRVE0227E" severity="E" prefix="yes">
  <MsgText pgmKey="class.resides.in.proper.package.directory" varFormat="Java">
    class.resides.in.proper.package.directory=SRVE0227E: Check that the class resides in the proper package directory.
  </MsgText>
  <Explanation>
    Package name of resource does not match the compiled class file&apos;s package. This is an application error.
  </Explanation>
  <UserResponse>
    Check that the class resides in the proper package directory.
  </UserResponse>
</Message>
<Message ID="SRVE0209E" severity="E" prefix="yes">
  <MsgText pgmKey="Writer.already.obtained" varFormat="Java">
    Writer.already.obtained=SRVE0209E: Writer already obtained
  </MsgText>
  <Explanation>
    The writer for this response has already been obtained. Use the existing writer. This is an application error.
  </Explanation>
  <UserResponse>
    Review application to determine if both PrintWriter and OuputStream were obtained. Modify the failing servlet/JSP to only obtain one or the other.
  </UserResponse>
</Message>
<Message ID="SRVE0080E" severity="E" prefix="yes">
  <MsgText pgmKey="Invalid.Content.Length" varFormat="Java">
    Invalid.Content.Length=SRVE0080E: Invalid content length
  </MsgText>
  <Explanation>
    The content length does not match the length of the post data. This is an application error.
  </Explanation>
  <UserResponse>
    Investigate the client to determine why the content-length field does not match the size of the post data. If the client is setting it correctly, investigate where in the network the content-length field becomes invalid.
  </UserResponse>
</Message>
<Message ID="SRVE0299E" severity="E" prefix="yes">
  <MsgText pgmKey="could.not.create.wrapper.for.servlet" varFormat="Java">
    could.not.create.wrapper.for.servlet=SRVE0299E: Could not create wrapper for servlet [{0}]
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0302E" severity="E" prefix="yes">
  <MsgText pgmKey="error.while.adding.static.file.processor" varFormat="Java">
    error.while.adding.static.file.processor=SRVE0302E: Error while adding static file processor: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8038E" severity="E" prefix="yes">
  <MsgText pgmKey="trying.to.do.startAsync.after.a.complete" varFormat="Java">
    trying.to.do.startAsync.after.a.complete=SRVE8038E: Trying to do startAsync after a complete.
  </MsgText>
  <Explanation>
    The method startAsync cannot be called after a complete per the Servlet specification.
  </Explanation>
  <UserResponse>
    Verify there are no code logic or timing issues causing this illegal behavior.
  </UserResponse>
</Message>
<Message ID="SRVE0259W" severity="W" prefix="yes">
  <MsgText pgmKey="property.configuration.change" varFormat="Java">
    property.configuration.change=SRVE0259W: The {0} property is now configurable only at the web container level.
  </MsgText>
  <Explanation>
    The property can no longer be configured at the transport level and must be configured at the web container level. System action is required.
  </Explanation>
  <UserResponse>
    Configure this property at the web container level.
  </UserResponse>
</Message>
<Message ID="SRVE0217E" severity="E" prefix="yes">
  <MsgText pgmKey="{0}.is.not.a.valid.class" varFormat="Java">
    {0}.is.not.a.valid.class=SRVE0217E: {0} is not a valid class
  </MsgText>
  <Explanation>
    This error occurred when the web container tried to load an internal implementation class. This is a system error.
  </Explanation>
  <UserResponse>
    Check to make sure the original product class path has not been modified.
  </UserResponse>
</Message>
<Message ID="SRVE8080E" severity="E" prefix="yes">
  <MsgText pgmKey="isUserInRole.caught.exception" varFormat="Java">
    isUserInRole.caught.exception=SRVE8080E: Unexpected isUserInRole exception, returning of isUserInRole false.
  </MsgText>
  <Explanation>
    Unexpected isUserInRole exception, returning of isUserInRole false.
  </Explanation>
  <UserResponse>
    Unexpected isUserInRole exception, returning of isUserInRole false.
  </UserResponse>
</Message>
<Message ID="SRVE0126E" severity="E" prefix="yes">
  <MsgText pgmKey="Invalidation.Exception:.{0}.was.created" varFormat="Java">
    Invalidation.Exception:.{0}.was.created=SRVE0126E: Invalidation Exception: {0} was created
  </MsgText>
  <Explanation>
    This is an internal system error and is probably caused by an earlier failure.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE8068E" severity="E" prefix="yes">
  <MsgText pgmKey="Could.not.remove.webmodule" varFormat="Java">
    Could.not.remove.webmodule=SRVE8068E: Could not remove the web module [{0}]
  </MsgText>
  <Explanation>
    An unexpected exception occurred removing the web module.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8032W" severity="W" prefix="yes">
  <MsgText pgmKey="exception.occurred.while.initializing.ServletContainerInitializers.HandlesTypes" varFormat="Java">
    exception.occurred.while.initializing.ServletContainerInitializers.HandlesTypes=SRVE8032W: A problem finding a HandlesTypes class during the scan of the ServletContainerInitializer, {0}, for {1}.
  </MsgText>
  <Explanation>
    The class was not found in the class loader when processing the ServletContainerInitializer HandlesTypes annotation.
  </Explanation>
  <UserResponse>
    Make sure the class exists within the web module&apos;s class loader.
  </UserResponse>
</Message>
<Message ID="SRVE8046E" severity="E" prefix="yes">
  <MsgText pgmKey="error.calling.async.dispatch" varFormat="Java">
    error.calling.async.dispatch=SRVE8046E: An error occurred while invoking a call to AsyncContext dispatch.
  </MsgText>
  <Explanation>
    An error occurred while invoking a call to AsyncContext dispatch.
  </Explanation>
  <UserResponse>
    See the root cause of the exception.
  </UserResponse>
</Message>
<Message ID="SRVE0285E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.caught.destroying.context" varFormat="Java">
    exception.caught.destroying.context=SRVE0285E: Exception caught while destroying context: {0}
  </MsgText>
  <Explanation>
    This is a system error error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8003E" severity="E" prefix="yes">
  <MsgText pgmKey="add.servlet.mapping.to.null.url.patterns" varFormat="Java">
    add.servlet.mapping.to.null.url.patterns=SRVE8003E: Attempted to add a servlet mapping with the variable argument url pattern parameter set to null.
  </MsgText>
  <Explanation>
    The variable argument url-pattern parameter passed to ServletRegistration.addMapping must be non-null and non-empty.
  </Explanation>
  <UserResponse>
    Modify application code according to error explanation.
  </UserResponse>
</Message>
<Message ID="SRVE8095W" severity="W" prefix="yes">
  <MsgText pgmKey="async.servlet.work.rejected" varFormat="Java">
    async.servlet.work.rejected=SRVE8095W: workRejected was called for the runnable [{0}].
  </MsgText>
  <Explanation>
    When scheduling a work item with an asynchronous beans work manager, workRejected may be called if an error happens starting the work item.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0282E" severity="E" prefix="yes">
  <MsgText pgmKey="error.while.setting.WebAppAttributes" varFormat="Java">
    error.while.setting.WebAppAttributes=SRVE0282E: Error occured while setting web application attribues: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0252W" severity="W" prefix="yes">
  <MsgText pgmKey="transports.detected" varFormat="Java">
    transports.detected=SRVE0252W: Transports and Chains have been detected! The transports have been changed to use a new model. Use the migration utilities to migrate the transports to the new model. The thread pool configuration under the web container will not be used with these transports.
  </MsgText>
  <Explanation>
    Transports have been changed to use Channel Chains. Refer to the information center to review information on Channel Chains, and how to migrate the existing transports to be channel chain based. The thread pool configuration under the web container will not be used to these transports.
  </Explanation>
  <UserResponse>
    Use the migration utilities to migrate your configuration model from the transports to the new channel chains.
  </UserResponse>
</Message>
<Message ID="SRVE0220I" severity="I" prefix="yes">
  <MsgText pgmKey="Wrapped.Error" varFormat="Java">
    Wrapped.Error=SRVE0220I: Wrapped Error-
  </MsgText>
  <Explanation>
    Error that caused the problem.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8052E" severity="E" prefix="yes">
  <MsgText pgmKey="classnotfoundexception.loading.servlet.class" varFormat="Java">
    classnotfoundexception.loading.servlet.class=SRVE8052E: Logging ClassNotFoundException
  </MsgText>
  <Explanation>
    Servlet could not find a required class needed to service the request. This is an application error.
  </Explanation>
  <UserResponse>
    Verify the class exists within the application.
  </UserResponse>
</Message>
<Message ID="SRVE0014E" severity="E" prefix="yes">
  <MsgText pgmKey="Uncaught.service().exception.root.cause" varFormat="Java">
    Uncaught.service().exception.root.cause=SRVE0014E: Uncaught service() exception root cause {0}: {1}
  </MsgText>
  <Explanation>
    Uncaught exception created in servlet service method. This is an application error.
  </Explanation>
  <UserResponse>
    Varies by root cause.
  </UserResponse>
</Message>
<Message ID="SRVE8073E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.webApp.configuration.object" varFormat="Java">
    Null.webApp.configuration.object=SRVE8073E: Null web application configuration object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0185E" severity="E" prefix="yes">
  <MsgText pgmKey="error.occurred.processing.request" varFormat="Java">
    error.occurred.processing.request=SRVE0185E: An error has occurred while processing request:
  </MsgText>
  <Explanation>
    Exception that occurred when processing the request.
  </Explanation>
  <UserResponse>
    Review the message to determine the root cause of the problem.
  </UserResponse>
</Message>
<Message ID="SRVE8504W" severity="W" prefix="yes">
  <MsgText pgmKey="uncaught.exception.during.AsyncListener.onComplete" varFormat="Java">
    uncaught.exception.during.AsyncListener.onComplete=SRVE8504W: The following uncaught exception was thrown by the AsyncListener: [{0}] during onComplete: [{1}]
  </MsgText>
  <Explanation>
    The AsyncListener that is referenced in the error message threw an Exception. The Exception is an application error.
  </Explanation>
  <UserResponse>
    Verify the AsyncListener source code and the server logs for the root cause of the application error.
  </UserResponse>
</Message>
<Message ID="SRVE0070E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.Initializing.for.Next.Request" varFormat="Java">
    Error.Initializing.for.Next.Request=SRVE0070E: Error initializing for next request
  </MsgText>
  <Explanation>
    Internal web container error.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0199E" severity="E" prefix="yes">
  <MsgText pgmKey="OutputStream.already.obtained" varFormat="Java">
    OutputStream.already.obtained=SRVE0199E: OutputStream already obtained
  </MsgText>
  <Explanation>
    Application requested a PrintWriter after the ServletResponse OutputStream had already been obtained. This is an application error.
  </Explanation>
  <UserResponse>
    Review application to determine if both PrintWriter and OuputStream were obtained. Modify the failing servlet/JSP to only obtain one or the other.
  </UserResponse>
</Message>
<Message ID="SRVE8036E" severity="E" prefix="yes">
  <MsgText pgmKey="InstantiationException.loading.servlet" varFormat="Java">
    InstantiationException.loading.servlet=SRVE8036E: Servlet [{0}]: {1} could not be loaded due to an InstantiationException.
  </MsgText>
  <Explanation>
    An InstantiationException occurs when trying to create a new instance of an interface or abstract class.
  </Explanation>
  <UserResponse>
    Change the class being instantiated to a concrete class or remove the definition as a servlet.
  </UserResponse>
</Message>
<Message ID="SRVE0053E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Invalid.Date.Format" varFormat="Java">
    Illegal.Argument:.Invalid.Date.Format=SRVE0053E: Illegal Argument Exception: Invalid date format
  </MsgText>
  <Explanation>
    Date format is not valid.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE0262E" severity="E" prefix="yes">
  <MsgText pgmKey="annotation.helper.wrong.type" varFormat="Java">
    annotation.helper.wrong.type=SRVE0262E: The annotation helper {0} is not of type com.ibm.wsspi.webcontainer.AnnotationHelper.
  </MsgText>
  <Explanation>
    The specified annotation helper is not of the expected type. This is a system error.
  </Explanation>
  <UserResponse>
    Check the annotation helper implementation class and fix it.
  </UserResponse>
</Message>
<Message ID="SRVE8103E" severity="E" prefix="yes">
  <MsgText pgmKey="Exception.creating.channel" varFormat="Java">
    Exception.creating.channel=SRVE8103E: An internal server error occurred creating the channel object.
  </MsgText>
  <Explanation>
    An internal server error occurred creating the channel object.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM support.
  </UserResponse>
</Message>
<Message ID="SRVE8057E" severity="E" prefix="yes">
  <MsgText pgmKey="error.initializing.output.stream" varFormat="Java">
    error.initializing.output.stream=SRVE8057E: An unexpected exception occurred initializing the output stream.
  </MsgText>
  <Explanation>
    An unexpected exception occurred initializing the output stream.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0121E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Trying.to.write.&lt;.0.bytes" varFormat="Java">
    Illegal.Argument:.Trying.to.write.&lt;.0.bytes=SRVE0121E: Illegal Argument Exception: Trying to write &amp;lt; 0 bytes
  </MsgText>
  <Explanation>
    Attempting to output a buffer of size less than 0. This is an application error.
  </Explanation>
  <UserResponse>
    Only write buffers of size of 0 or greater.
  </UserResponse>
</Message>
<Message ID="SRVE8094W" severity="W" prefix="yes">
  <MsgText pgmKey="Cannot.set.header.Response.already.committed" varFormat="Java">
    Cannot.set.header.Response.already.committed=SRVE8094W: WARNING: Cannot set header. Response already committed.
  </MsgText>
  <Explanation>
    Once a response is committed, you cannot set more response headers.
  </Explanation>
  <UserResponse>
    Verify whether this call is necessary. If the header really needs to be sent, it should be set before committing the response.
  </UserResponse>
</Message>
<Message ID="SRVE0312E" severity="E" prefix="yes">
  <MsgText pgmKey="error.adding.channel" varFormat="Java">
    error.adding.channel=SRVE0312E: There was an adding while adding a channel: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0317W" severity="W" prefix="yes">
  <MsgText pgmKey="need.to.add.a.new.virtual.host.alias" varFormat="Java">
    need.to.add.a.new.virtual.host.alias=SRVE0317W: You may need to add a new virtual host alias of *:&lt;your port&gt; to the same virtual host that [{0}] is under.
  </MsgText>
  <Explanation>
    The request path maps to a context root on a non-matching virtual host.
  </Explanation>
  <UserResponse>
    Follow the instructions in the Information Center to add a new virtual host alias.
  </UserResponse>
</Message>
<Message ID="SRVE8000W" severity="W" prefix="yes">
  <MsgText pgmKey="ClassNotFound.check.web.xml" varFormat="Java">
    ClassNotFound.check.web.xml=SRVE8000W: Skipped class that failed to initialize for annotation scanning.
  </MsgText>
  <Explanation>
    A class in the web module could not be initialized so it cannot be scanned for annotations.
  </Explanation>
  <UserResponse>
    Verify the class exists and has all of its dependencies in the classpath.
  </UserResponse>
</Message>
<Message ID="SRVE8020E" severity="E" prefix="yes">
  <MsgText pgmKey="multipart.no.multipart.config" varFormat="Java">
    multipart.no.multipart.config=SRVE8020E: Servlet does not accept multipart requests
  </MsgText>
  <Explanation>
    The servlet does not accept multipart requests.
  </Explanation>
  <UserResponse>
    Add a @MultipartConfig annotation to this servlet or add a multipart-config element to this servlet in the web.xml.
  </UserResponse>
</Message>
<Message ID="SRVE8090E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.occurred.while.preparing.the.servlet.for.initialization" varFormat="Java">
    Error.occurred.while.preparing.the.servlet.for.initialization=SRVE8090E: Error occurred while preparing the servlet wrapper for initialization.
  </MsgText>
  <Explanation>
    Error occurred while preparing the servlet wrapper for initialization.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0322E" severity="E" prefix="yes">
  <MsgText pgmKey="Listener.found.but.injection.failure" varFormat="Java">
    Listener.found.but.injection.failure=SRVE0322E: The [{0}] listener class was found, but a resource injection failure has occurred.
  </MsgText>
  <Explanation>
    The listener failed to initialize because an error occured when a resource was injected.
  </Explanation>
  <UserResponse>
    Verify that the injected resources exist and are accessible to the listener. To re-initialize the listener, restart the listener application.
  </UserResponse>
</Message>
<Message ID="SRVE8026E" severity="E" prefix="yes">
  <MsgText pgmKey="thread.interrupted.scheduling.async.runnable.on.thread.pool" varFormat="Java">
    thread.interrupted.scheduling.async.runnable.on.thread.pool=SRVE8026E: An exception occurred scheduling work related to async servlet processing.
  </MsgText>
  <Explanation>
    This exception should never occur as the thread pools will queue up the work.
  </Explanation>
  <UserResponse>
    If this exception occurs, please contact support.
  </UserResponse>
</Message>
<Message ID="SRVE8108W" severity="W" prefix="yes">
  <MsgText pgmKey="trying.to.set.number.of.async.timer.threads.to.less.than.one" varFormat="Java">
    trying.to.set.number.of.async.timer.threads.to.less.than.one=SRVE8108W: Trying to set number of async timer threads to less than one.
  </MsgText>
  <Explanation>
    There must be at least one async timer thread.
  </Explanation>
  <UserResponse>
    Check your server configuration to see what the value is set to.
  </UserResponse>
</Message>
<Message ID="SRVE0011E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument.Trying.to.write.chars" varFormat="Java">
    Illegal.Argument.Trying.to.write.chars=SRVE0011E: Illegal Argument Exception: Trying to write &lt; 0 chars
  </MsgText>
  <Explanation>
    Attempting to output a buffer of size less than 0. This is an application error.
  </Explanation>
  <UserResponse>
    Only write buffers of size of 0 or greater.
  </UserResponse>
</Message>
<Message ID="SRVE0255E" severity="E" prefix="yes">
  <MsgText pgmKey="Web.Group.VHost.Not.Found" varFormat="Java">
    Web.Group.VHost.Not.Found=SRVE0255E: A WebGroup/Virtual Host to handle {0} has not been defined.
  </MsgText>
  <Explanation>
    Could not find a web group (web module) or virtual host to handle the request. This is an application error.
  </Explanation>
  <UserResponse>
    Be sure the web group and virtual host is defined and deployed.
  </UserResponse>
</Message>
<Message ID="SRVE0279E" severity="E" prefix="yes">
  <MsgText pgmKey="error.processing.global.listeners.for.webapp" varFormat="Java">
    error.processing.global.listeners.for.webapp=SRVE0279E: Error occured while processing global listeners for the application {0}: {1}
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0238E" severity="E" prefix="yes">
  <MsgText pgmKey="resource.path.has.to.start.with.slash" varFormat="Java">
    resource.path.has.to.start.with.slash=SRVE0238E: Resource paths should have a leading slash
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Supply a leading slash before the path and try again.
  </UserResponse>
</Message>
<Message ID="SRVE0140E" severity="E" prefix="yes">
  <MsgText pgmKey="instantiate.collaborator.exception" varFormat="Java">
    instantiate.collaborator.exception=SRVE0140E: Could not instantiate the security collaborator {0}
  </MsgText>
  <Explanation>
    Internal server error.
  </Explanation>
  <UserResponse>
    Gather logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8048E" severity="E" prefix="yes">
  <MsgText pgmKey="mapping.clash.occurred" varFormat="Java">
    mapping.clash.occurred=SRVE8048E: A mapping clash occurred when adding the url pattern [{0}]
  </MsgText>
  <Explanation>
    The same pattern was specified twice for the url patterns to deny for file serving.
  </Explanation>
  <UserResponse>
    Please check the file serving attributes in your ibm-web-ext.xmi or ibm-web-ext.xml file.
  </UserResponse>
</Message>
<Message ID="SRVE0272W" severity="W" prefix="yes">
  <MsgText pgmKey="jsp.processor.not.defined.skipping" varFormat="Java">
    jsp.processor.not.defined.skipping=SRVE0272W: JSP Processor not defined. Skipping : {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8017E" severity="E" prefix="yes">
  <MsgText pgmKey="error.validate.webServlet.urlPatterns.and.value" varFormat="Java">
    error.validate.webServlet.urlPatterns.and.value=SRVE8017E: The class, {0}, can not specify both urlPatterns and value in the annotation
  </MsgText>
  <Explanation>
    The class can not specify both urlPatterns and value in the annotation
  </Explanation>
  <UserResponse>
    Modify the class to only include one of the urlPatterns or value attribute
  </UserResponse>
</Message>
<Message ID="SRVE0225I" severity="I" prefix="yes">
  <MsgText pgmKey="Root.Error" varFormat="Java">
    Root.Error=SRVE0225I: Root Error-
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0160E" severity="E" prefix="yes">
  <MsgText pgmKey="usertransaction.rollback.exception" varFormat="Java">
    usertransaction.rollback.exception=SRVE0160E: Exception while rolling back UserTransaction: {0}
  </MsgText>
  <Explanation>
    Problem encountered rolling back the specified user transaction. This is an application error.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE0108E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Missing.flag.value" varFormat="Java">
    Illegal.Argument:.Missing.flag.value=SRVE0108E: Illegal Argument Exception: Missing flag value
  </MsgText>
  <Explanation>
    Missing flag value.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE8056E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.while.closing.response.output" varFormat="Java">
    Error.while.closing.response.output=SRVE8056E: An unexpected exception occurred closing the output stream.
  </MsgText>
  <Explanation>
    An unexpected exception occurred closing the output stream.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0313E" severity="E" prefix="yes">
  <MsgText pgmKey="transport.migration.error" varFormat="Java">
    transport.migration.error=SRVE0313E: Error occured while migrating transport at port {0} to the corresponding chain: {1}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0239I" severity="I" prefix="yes">
  <MsgText pgmKey="ExtensionFactory.[{0}].registered.successfully" varFormat="Java">
    ExtensionFactory.[{0}].registered.successfully=SRVE0239I: Extension Factory [{0}] was registered successfully.
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0201E" severity="E" prefix="yes">
  <MsgText pgmKey="Servlet.not.a.servlet.class" varFormat="Java">
    Servlet.not.a.servlet.class=SRVE0201E: Servlet [{0}]: not a servlet class
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Modify the failing class to implement javax.servlet.Servlet or extend one of javax.servlet.GenericServlet or javax.servlet.http.HttpServlet
  </UserResponse>
</Message>
<Message ID="SRVE0291E" severity="E" prefix="yes">
  <MsgText pgmKey="unable.to.use.default.temp.directory" varFormat="Java">
    unable.to.use.default.temp.directory=SRVE0291E: Unable to use default temp directory: {0} read:{1} write:{2}
  </MsgText>
  <Explanation>
    System action is required.
  </Explanation>
  <UserResponse>
    Check the status of the directory, including existence, access privileges and available space.
  </UserResponse>
</Message>
<Message ID="SRVE0214E" severity="E" prefix="yes">
  <MsgText pgmKey="invalid.count" varFormat="Java">
    invalid.count=SRVE0214E: invalid count
  </MsgText>
  <Explanation>
    Internal exception.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="SRVE0271E" severity="E" prefix="yes">
  <MsgText pgmKey="uncaught.init.exception.thrown.by.servlet" varFormat="Java">
    uncaught.init.exception.thrown.by.servlet=SRVE0271E: Uncaught init() exception created by servlet [{0}] in application [{1}]: {2}
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0096E" severity="E" prefix="yes">
  <MsgText pgmKey="Session.Feature.Set.Not.Started" varFormat="Java">
    Session.Feature.Set.Not.Started=SRVE0096E: A session cannot be accessed.  The session manager feature set has not been started.
  </MsgText>
  <Explanation>
    A session cannot be accessed.  The session manager feature set has not been started.
  </Explanation>
  <UserResponse>
    Make sure that the server configuration depends upon the session feature set.
  </UserResponse>
</Message>
<Message ID="SRVE8008E" severity="E" prefix="yes">
  <MsgText pgmKey="add.filter.mapping.to.empty.servlet.names" varFormat="Java">
    add.filter.mapping.to.empty.servlet.names=SRVE8008E: Attempted to add a filter mapping with an empty variable argument servlet name parameter.
  </MsgText>
  <Explanation>
    The variable argument servlet name parameter passed to FilterRegistration.addMappingForServletNames must be non-null and non-empty.
  </Explanation>
  <UserResponse>
    Modify application code according to error explanation.
  </UserResponse>
</Message>
<Message ID="SRVE8087E" severity="E" prefix="yes">
  <MsgText pgmKey="error.creating.stats.instance" varFormat="Java">
    error.creating.stats.instance=SRVE8087E: Error creating PMI statistics instance.
  </MsgText>
  <Explanation>
    The createStatsInstance() method created an exception when it was called to create the statistics instance. No statistic were collected.
  </Explanation>
  <UserResponse>
    Examine the server logs to determine the root cause of the problem.
  </UserResponse>
</Message>
<Message ID="SRVE0229E" severity="E" prefix="yes">
  <MsgText pgmKey="class.transfered.using.binary.mode" varFormat="Java">
    class.transfered.using.binary.mode=SRVE0229E: Check that the class was transferred to the filesystem using a binary transfer mode.
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Check that the class was transferred to the filesystem using a binary transfer mode.
  </UserResponse>
</Message>
<Message ID="SRVE0095I" severity="I" prefix="yes">
  <MsgText pgmKey="Servlet.has.become.temporarily.unavailable.for.service:.{0}" varFormat="Java">
    Servlet.has.become.temporarily.unavailable.for.service:.{0}=SRVE0095I: Servlet has become temporarily unavailable for service: {0}
  </MsgText>
  <Explanation>
    Specified servlet is temporarily unavailable.
  </Explanation>
  <UserResponse>
    Wait and retry operation.  Servlet might have been removed from service by server administrator.
  </UserResponse>
</Message>
<Message ID="SRVE8100W" severity="W" prefix="yes">
  <MsgText pgmKey="virtual.host.alias.clash" varFormat="Java">
    virtual.host.alias.clash=SRVE8100W: VirtualHost alias already exists for this VirtualHost --&gt;[{0}].
  </MsgText>
  <Explanation>
    There was an error adding a virtual host alias because one already exists with the same pattern.
  </Explanation>
  <UserResponse>
    Edit your virtual host alias and remove any duplicates.
  </UserResponse>
</Message>
<Message ID="SRVE0157E" severity="E" prefix="yes">
  <MsgText pgmKey="setbuffer.size.called.after.write" varFormat="Java">
    setbuffer.size.called.after.write=SRVE0157E: setBufferSize() called after first write to Output Stream/Writer
  </MsgText>
  <Explanation>
    An attempt was made to set the response buffer size after the response was already committed. This is an application error.
  </Explanation>
  <UserResponse>
    Remove the setBufferSize() call or move it to a position before the response commit.
  </UserResponse>
</Message>
<Message ID="SRVE0267E" severity="E" prefix="yes">
  <MsgText pgmKey="error.initializing.filters" varFormat="Java">
    error.initializing.filters=SRVE0267E: Error occured while initializing filters: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8065E" severity="E" prefix="yes">
  <MsgText pgmKey="webcontianer.configuration.error" varFormat="Java">
    webcontianer.configuration.error=SRVE8065E: Unknown error related to the web container configuration.
  </MsgText>
  <Explanation>
    Unknown error related to the web container configuration.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8059E" severity="E" prefix="yes">
  <MsgText pgmKey="unable.to.get.sessionContext" varFormat="Java">
    unable.to.get.sessionContext=SRVE8059E: An unexpected exception occurred when trying to retrieve the session context
  </MsgText>
  <Explanation>
    An unexpected exception occurred when trying to retrieve the session context
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0236E" severity="E" prefix="yes">
  <MsgText pgmKey="error.on.collaborator.starting.call" varFormat="Java">
    error.on.collaborator.starting.call=SRVE0236E: Error occurred while invoking initialization collaborator on starting() call
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Check the FFDC logs for more details on the error.
  </UserResponse>
</Message>
<Message ID="SRVE0041E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Bootstrap.File.Not.Found" varFormat="Java">
    Illegal.Argument:.Bootstrap.File.Not.Found=SRVE0041E: Illegal Argument Exception: Bootstrap file not found
  </MsgText>
  <Explanation>
    This is an internal system error and is probably caused by an earlier failure.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE8097W" severity="W" prefix="yes">
  <MsgText pgmKey="null.url.pattern.and.servlet.name.for.filter.mapping" varFormat="Java">
    null.url.pattern.and.servlet.name.for.filter.mapping=SRVE8097W: No url pattern or servlet name for filter mapping for filter named [{0}].
  </MsgText>
  <Explanation>
    A filter mapping is incomplete without a url pattern or servlet name to map to.
  </Explanation>
  <UserResponse>
    Add a url pattern or servlet name to the filter mapping.
  </UserResponse>
</Message>
<Message ID="SRVE8111E" severity="E" prefix="yes">
  <MsgText pgmKey="programmatic.session.cookie.restricted.match" varFormat="Java">
    programmatic.session.cookie.restricted.match=SRVE8111E: The application, {0}, is trying to modify a cookie which matches a pattern in the restricted programmatic session cookies list [domain={1}, name={2}, path={3}].
  </MsgText>
  <Explanation>
    The administrator has disabled changing the cookie configuration for the cookie matching the domain, name, and path
  </Explanation>
  <UserResponse>
    Either modify the application to use a different cookie name, domain, or path or modify the restricted programmatic session cookie values
  </UserResponse>
</Message>
<Message ID="SRVE0256E" severity="E" prefix="yes">
  <MsgText pgmKey="webcontainer.not.initialized" varFormat="Java">
    webcontainer.not.initialized=SRVE0256E: Web Container has not been initialized.
  </MsgText>
  <Explanation>
    Web Container is not initialized until an application has been installed. This is a system error.
  </Explanation>
  <UserResponse>
    Install an application to initialize the web container.
  </UserResponse>
</Message>
<Message ID="SRVE0233E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.Report" varFormat="Java">
    Error.Report=SRVE0233E: Error Report
  </MsgText>
  <Explanation>
    none
  </Explanation>
  <UserResponse>
    none
  </UserResponse>
</Message>
<Message ID="SRVE0283E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.while.initializing.context" varFormat="Java">
    exception.while.initializing.context=SRVE0283E: Exception caught while initializing context: {0}
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0237E" severity="E" prefix="yes">
  <MsgText pgmKey="error.on.collaborator.started.call" varFormat="Java">
    error.on.collaborator.started.call=SRVE0237E: Error occurred while invoking initialization collaborator on started() call
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Check the FFDC logs for more details on the error
  </UserResponse>
</Message>
<Message ID="SRVE8035E" severity="E" prefix="yes">
  <MsgText pgmKey="IllegalAccessException.loading.servlet" varFormat="Java">
    IllegalAccessException.loading.servlet=SRVE8035E: Servlet [{0}]: {1} could not be loaded due to an IllegalAccessException.
  </MsgText>
  <Explanation>
    An IllegalAccessException occurred calling newInstance on the servlet.
  </Explanation>
  <UserResponse>
    Verify there is a public no argument constructor on the servlet.
  </UserResponse>
</Message>
<Message ID="SRVE8063E" severity="E" prefix="yes">
  <MsgText pgmKey="Could.not.create.LoginProcessor" varFormat="Java">
    Could.not.create.LoginProcessor=SRVE8063E: An unexpected exception occurred initializing the login processor.
  </MsgText>
  <Explanation>
    An unexpected exception occurred initializing the login processor.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0180I" severity="I" prefix="yes">
  <MsgText pgmKey="[{0}][{1}][Servlet.LOG]:.{2}" varFormat="Java">
    [{0}][{1}][Servlet.LOG]:.{2}=SRVE0180I: [{0}] [{1}] [Servlet.LOG]: {2}
  </MsgText>
  <Explanation>
    Informational message logged via ServletContext.log from an application.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0216E" severity="E" prefix="yes">
  <MsgText pgmKey="post.body.contains.less.bytes.than.specified" varFormat="Java">
    post.body.contains.less.bytes.than.specified=SRVE0216E: post body contains less bytes than specified by content-length
  </MsgText>
  <Explanation>
    The incoming request may be corrupted. This is an application error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8067E" severity="E" prefix="yes">
  <MsgText pgmKey="Failed.to.handle.extension.point" varFormat="Java">
    Failed.to.handle.extension.point=SRVE8067E: An unexpected exception occurred handling an extension point.
  </MsgText>
  <Explanation>
    An unexpected exception occurred handling an extension point.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8058E" severity="E" prefix="yes">
  <MsgText pgmKey="Did.not.have.access.to.delete.Directory" varFormat="Java">
    Did.not.have.access.to.delete.Directory=SRVE8058E: Did not have access to delete the temporary directory
  </MsgText>
  <Explanation>
    Java 2 Security policy prevented deleting the temporary directory
  </Explanation>
  <UserResponse>
    Check Java 2 Security policy to verify whether this access should be allowed.
  </UserResponse>
</Message>
<Message ID="SRVE8015E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.occurred.while.adding.listener" varFormat="Java">
    exception.occurred.while.adding.listener=SRVE8015E: An exception occurred while trying to add a listener of type {0}
  </MsgText>
  <Explanation>
    An exception occurred while trying to add a listener
  </Explanation>
  <UserResponse>
    Verify the listener is a valid type and available to the application
  </UserResponse>
</Message>
<Message ID="SRVE0163I" severity="I" prefix="yes">
  <MsgText pgmKey="web.container.jsp.spec.level" varFormat="Java">
    web.container.jsp.spec.level=SRVE0163I: Supported JSP Specification Level: 2.2
  </MsgText>
  <Explanation>
    The JSP specification level supported by the application server.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8077E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.webApp.config.object" varFormat="Java">
    Null.webApp.config.object=SRVE8077E: Null web application config object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0066I" severity="I" prefix="yes">
  <MsgText pgmKey="Waiting.servlet.to.finish.servicing.requests:.{0}" varFormat="Java">
    Waiting.servlet.to.finish.servicing.requests:.{0}=SRVE0066I: Waiting for servlet to finish servicing requests: {0}
  </MsgText>
  <Explanation>
    Servlet is still handling the request. Waiting for request to complete before calling destroy.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8109W" severity="W" prefix="yes">
  <MsgText pgmKey="uncaught.filter.exception" varFormat="Java">
    uncaught.filter.exception=SRVE8109W: Uncaught exception thrown by filter {0}: {1}
  </MsgText>
  <Explanation>
    An exception was thrown from a filter.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0188E" severity="E" prefix="yes">
  <MsgText pgmKey="Class.{0}.does.not.implement.servlet" varFormat="Java">
    Class.{0}.does.not.implement.servlet=SRVE0188E: Class {0} does not implement servlet
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    =The class mentioned needs to implement javax.servlet.Servlet or extend one of javax.servlet.GenericServlet or javax.servlet.http.HttpServlet
  </UserResponse>
</Message>
<Message ID="SRVE0231E" severity="E" prefix="yes">
  <MsgText pgmKey="class.not.renamed.after.compiled" varFormat="Java">
    class.not.renamed.after.compiled=SRVE0231E: Check that the class file was not renamed after it was compiled.
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Check that the class file was not renamed after it was compiled.
  </UserResponse>
</Message>
<Message ID="SRVE0319E" severity="E" prefix="yes">
  <MsgText pgmKey="Servlet.found.but.injection.failure" varFormat="Java">
    Servlet.found.but.injection.failure=SRVE0319E: For the [{0}] servlet, {1} servlet class was found, but a resource injection failure has occurred.
  </MsgText>
  <Explanation>
    The servlet failed to initialize because an error occurred when a resource was injected.
  </Explanation>
  <UserResponse>
    Verify that the injected resources exist and are accessible to the servlet.
  </UserResponse>
</Message>
<Message ID="SRVE0241I" severity="I" prefix="yes">
  <MsgText pgmKey="Using.[{0}].as.server.root" varFormat="Java">
    Using.[{0}].as.server.root=SRVE0241I: Using [{0}] as the server root in getTempDirectory().
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8086E" severity="E" prefix="yes">
  <MsgText pgmKey="invalid.peer.certificate" varFormat="Java">
    invalid.peer.certificate=SRVE8086E: Invalid peer certificate.
  </MsgText>
  <Explanation>
    An exception occurred retrieving the peer certificate.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0055I" severity="I" prefix="yes">
  <MsgText pgmKey="Servlet.wait.for.destroy.timeout.has.expired,.destroy.will.be.forced:.{0}" varFormat="Java">
    Servlet.wait.for.destroy.timeout.has.expired,.destroy.will.be.forced:.{0}=SRVE0055I: Servlet wait for destroy time-out has expired, destroy will be forced: {0}
  </MsgText>
  <Explanation>
    Servlet is being destroyed after wait has timed out.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0318W" severity="W" prefix="yes">
  <MsgText pgmKey="invalid.query.string" varFormat="Java">
    invalid.query.string=SRVE0318W: Invalid character in query string.
  </MsgText>
  <Explanation>
    A character, which is not valid, exists in the query string and has been ignored.
  </Explanation>
  <UserResponse>
    A user action is not required.
  </UserResponse>
</Message>
<Message ID="SRVE8014E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.occurred.while.creating.listener.instance" varFormat="Java">
    exception.occurred.while.creating.listener.instance=SRVE8014E: An exception occurred while creating the listener instance
  </MsgText>
  <Explanation>
    An exception occurred while creating the listener instance
  </Explanation>
  <UserResponse>
    An exception occurred while creating the listener instance
  </UserResponse>
</Message>
<Message ID="SRVE8047E" severity="E" prefix="yes">
  <MsgText pgmKey="NumberFormatException.for.file.size.at.which.you.switch.to.optimized.file.serving" varFormat="Java">
    NumberFormatException.for.file.size.at.which.you.switch.to.optimized.file.serving=SRVE8047E: NumberFormatException for file size at which you switch to optimized file serving.
  </MsgText>
  <Explanation>
    The file serving attribute com.ibm.ws.webcontainer.optimizefileservingsize could not be parsed property.
  </Explanation>
  <UserResponse>
    Change the value of the attribute to a valid integer value.
  </UserResponse>
</Message>
<Message ID="SRVE0187E" severity="E" prefix="yes">
  <MsgText pgmKey="Check.your.classpath.ensure.all.classes.present" varFormat="Java">
    Check.your.classpath.ensure.all.classes.present=SRVE0187E: Check your class path to ensure that all classes required by the servlet are present.
  </MsgText>
  <Explanation>
    A required class was not found. This is an application error.
  </Explanation>
  <UserResponse>
    Make sure your class path reflects all the classes you may be accessing
  </UserResponse>
</Message>
<Message ID="SRVE0015E" severity="E" prefix="yes">
  <MsgText pgmKey="Failed.to.initialize.webapp.{0}" varFormat="Java">
    Failed.to.initialize.webapp.{0}=SRVE0015E: Failure to initialize Web application {0}
  </MsgText>
  <Explanation>
    Could not initialize the web application specified in the message. Check the error log for more details.
  </Explanation>
  <UserResponse>
    Look in the error log to determine the root cause of this problem.
  </UserResponse>
</Message>
<Message ID="SRVE0286E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.caught.in.notifyServletContextDestroyed" varFormat="Java">
    exception.caught.in.notifyServletContextDestroyed=SRVE0286E: Exception caught in notifyServletContextDestroyed: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0263E" severity="E" prefix="yes">
  <MsgText pgmKey="annotation.helper.cannot.create" varFormat="Java">
    annotation.helper.cannot.create=SRVE0263E: The annotation helper {0} cannot be instantiated.
  </MsgText>
  <Explanation>
    The specified annotation helper could not be instantiated. This is a system error.
  </Explanation>
  <UserResponse>
    Check the exception logs for the reason that the annotation helper could not be instantiated.
  </UserResponse>
</Message>
<Message ID="SRVE8104E" severity="E" prefix="yes">
  <MsgText pgmKey="Servlet.Engine.Exception" varFormat="Java">
    Servlet.Engine.Exception=SRVE8104E: Internal Server Error. Exception Message: [{0}]
  </MsgText>
  <Explanation>
    An unexpected servlet engine exception occurred. This is a system error.
  </Explanation>
  <UserResponse>
    Check the System.out and System.err logs for more information on the exception generated.
  </UserResponse>
</Message>
<Message ID="SRVE0278E" severity="E" prefix="yes">
  <MsgText pgmKey="error.adding.servlet.mapping.file.handler" varFormat="Java">
    error.adding.servlet.mapping.file.handler=SRVE0278E: Error while adding servlet mapping --&gt; {0}.
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Set fileServingEnabled=false in the ibm-web-ext.xmi file which is under WEB-INF folder.
  </UserResponse>
</Message>
<Message ID="SRVE8074E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.webApp.object" varFormat="Java">
    Null.webApp.object=SRVE8074E: Null web application object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0274W" severity="W" prefix="yes">
  <MsgText pgmKey="error.while.adding.servlet.mapping.for.path" varFormat="Java">
    error.while.adding.servlet.mapping.for.path=SRVE0274W: Error while adding servlet mapping for path--&gt;{0}, wrapper--&gt;{1}, application--&gt;{2}.
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Check for mapping clash in webconfig.xml
  </UserResponse>
</Message>
<Message ID="SRVE0277W" severity="W" prefix="yes">
  <MsgText pgmKey="mapping.for.directorybrowsingservlet.already.exists" varFormat="Java">
    mapping.for.directorybrowsingservlet.already.exists=SRVE0277W: Mapping for DirectoryBrowsingServlet already exists
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Remove the duplicate mapping.
  </UserResponse>
</Message>
<Message ID="SRVE8037E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.handing.off.reference.data" varFormat="Java">
    exception.handing.off.reference.data=SRVE8037E: Exception processing reference data.
  </MsgText>
  <Explanation>
    An exception occurred processing reference data. Application will attempt to start anyway.
  </Explanation>
  <UserResponse>
    Investigate the root cause of the exception and determine if application still functions properly despite these failures.
  </UserResponse>
</Message>
<Message ID="SRVE0295E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.reported.{0}" varFormat="Java">
    Error.reported.{0}=SRVE0295E: Error reported: {0}
  </MsgText>
  <Explanation>
    HttpServletResponse.sendError was called with a status code but no explanation.
  </Explanation>
  <UserResponse>
    Review the logs to determine the status code of the error.
  </UserResponse>
</Message>
<Message ID="SRVE0056E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Unsupported.flag" varFormat="Java">
    Illegal.Argument:.Unsupported.flag=SRVE0056E: Illegal Argument Exception: Unsupported flag
  </MsgText>
  <Explanation>
    This is an internal system error and is probably caused by an earlier failure.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE0164E" severity="E" prefix="yes">
  <MsgText pgmKey="context.root.already.in.use" varFormat="Java">
    context.root.already.in.use=SRVE0164E: Web Application {0} uses the context root {1}, which is already in use by Web Application {2}. Web Application {3} will not be loaded.
  </MsgText>
  <Explanation>
    Two web applications on the same virtual host share the same context root. This is an application error.
  </Explanation>
  <UserResponse>
    Either change the context root of one of the web applications or move one to a different virtual host.
  </UserResponse>
</Message>
<Message ID="SRVE8088E" severity="E" prefix="yes">
  <MsgText pgmKey="failed.to.remove.pmi.stats" varFormat="Java">
    failed.to.remove.pmi.stats=SRVE8088E: Error removing PMI statistics instance.
  </MsgText>
  <Explanation>
    Error removing PMI statistics instance.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8019E" severity="E" prefix="yes">
  <MsgText pgmKey="error.validate.webServlet.name.empty" varFormat="Java">
    error.validate.webServlet.name.empty=SRVE8019E: Class, {0}, with annotation did not have a valid name
  </MsgText>
  <Explanation>
    The class must specify a valid name in the annotation
  </Explanation>
  <UserResponse>
    Modify the class to specify a valid name in the annotation
  </UserResponse>
</Message>
<Message ID="SRVE8005E" severity="E" prefix="yes">
  <MsgText pgmKey="add.filter.mapping.to.null.url.patterns" varFormat="Java">
    add.filter.mapping.to.null.url.patterns=SRVE8005E: Attempted to add a filter mapping with the variable argument url pattern parameter set to null.
  </MsgText>
  <Explanation>
    The variable argument url-pattern parameter passed to FilterRegistration.addMappingForUrlPatterns must be non-null and non-empty.
  </Explanation>
  <UserResponse>
    Modify application code according to error explanation.
  </UserResponse>
</Message>
<Message ID="SRVE0300E" severity="E" prefix="yes">
  <MsgText pgmKey="mapping.already.exists" varFormat="Java">
    mapping.already.exists=SRVE0300E: Mapping already Exists [{0}][{1}]: {2}
  </MsgText>
  <Explanation>
    The desired path is already assigned in a servlet mapping. This is an application error.
  </Explanation>
  <UserResponse>
    Change or remove the mapping from your application configuration.
  </UserResponse>
</Message>
<Message ID="SRVE0316W" severity="W" prefix="yes">
  <MsgText pgmKey="request.matches.context.root" varFormat="Java">
    request.matches.context.root=SRVE0316W: Request matches the context root [{0}] under the virtual host alias of [{1}].
  </MsgText>
  <Explanation>
    The request path maps to a context root on a non-matching virtual host.
  </Explanation>
  <UserResponse>
    Check to see if an additional virtual host alias needs to be added.
  </UserResponse>
</Message>
<Message ID="SRVE0210I" severity="I" prefix="yes">
  <MsgText pgmKey="be.debugged.by.recompiling.the.servlet.using.only.the.classes.in.the.application&apos;s.runtime.classpath" varFormat="Java">
    be.debugged.by.recompiling.the.servlet.using.only.the.classes.in.the.application&apos;s.runtime.classpath=SRVE0210I: This problem can be debugged by recompiling the servlet using only the classes in the application&apos;s runtime class path
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Recompile the servlet using only the classes in the application&apos;s runtime class path.
  </UserResponse>
</Message>
<Message ID="SRVE0206E" severity="E" prefix="yes">
  <MsgText pgmKey="This.error.implies.servlet.was.originally.compiled.with.classes.which.cannot.be.located.by.server" varFormat="Java">
    This.error.implies.servlet.was.originally.compiled.with.classes.which.cannot.be.located.by.server=SRVE0206E: This error typically implies that the servlet was originally compiled with classes which cannot be located by the server.
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Re-compile the servlet with all required components placed in the class path.
  </UserResponse>
</Message>
<Message ID="SRVE8055E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.while.flushing.last.response" varFormat="Java">
    Error.while.flushing.last.response=SRVE8055E: An unexpected exception occurred flushng out the rest of the response data.
  </MsgText>
  <Explanation>
    An unexpected exception occurred flushng out the rest of the response data.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8004E" severity="E" prefix="yes">
  <MsgText pgmKey="add.servlet.mapping.to.empty.url.patterns" varFormat="Java">
    add.servlet.mapping.to.empty.url.patterns=SRVE8004E: Attempted to add a servlet mapping with an empty variable argument url pattern parameter.
  </MsgText>
  <Explanation>
    The variable argument url-pattern parameter passed to ServletRegistration.addMapping must be non-null and non-empty.
  </Explanation>
  <UserResponse>
    Modify application code according to error explanation.
  </UserResponse>
</Message>
<Message ID="SRVE8025E" severity="E" prefix="yes">
  <MsgText pgmKey="error.occurred.during.async.servlet.handling" varFormat="Java">
    error.occurred.during.async.servlet.handling=SRVE8025E: An error or timeout occured while doing async servlet processing.
  </MsgText>
  <Explanation>
    An error or timeout resulting from an async dispatch will invoke any registered async listener and then the error page mechanism if not listener dispatches or completes.
  </Explanation>
  <UserResponse>
    Fix the cause of the error by looking at the exception and modifying application code or be sure to provide an AsyncListener or error page to gracefully handle the error case.
  </UserResponse>
</Message>
<Message ID="SRVE8013E" severity="E" prefix="yes">
  <MsgText pgmKey="Invalid.Listener" varFormat="Java">
    Invalid.Listener=SRVE8013E: Not a valid listener to add programmatically
  </MsgText>
  <Explanation>
    The listener being programmatically added does not implement a valid listener type
  </Explanation>
  <UserResponse>
    Modify the application code to add a listener of the accepted type
  </UserResponse>
</Message>
<Message ID="SRVE0189E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.occurred.while.finishing.request" varFormat="Java">
    Error.occurred.while.finishing.request=SRVE0189E: Error occurred while finishing request
  </MsgText>
  <Explanation>
    This is an error that occurs when the request was being completed. This could have happened because of a communication error within the Application Server but should not have affected the processing of the request. This is a system error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8500W" severity="W" prefix="yes">
  <MsgText pgmKey="servlet.with.same.name.already.exists" varFormat="Java">
    servlet.with.same.name.already.exists=SRVE8500W: A servlet named {0} can not be dynamically added because a servlet configuration with the same name already exists.
  </MsgText>
  <Explanation>
    A servlet with the same name already exists for this application.
  </Explanation>
  <UserResponse>
    No action necessary.  Check for conflicts in the deployment descriptor, annotations, and source code that could dynamically add this servlet configuration.
  </UserResponse>
</Message>
<Message ID="SRVE0296E" severity="E" prefix="yes">
  <MsgText pgmKey="log.servlet.message.with.throwable" varFormat="Java">
    log.servlet.message.with.throwable=SRVE0296E: [{0}][{1}][Servlet.LOG]:.{2}:.{3}
  </MsgText>
  <Explanation>
    Informational message and exception logged for a servlet by use of the ServletContext..
  </Explanation>
  <UserResponse>
    Review the message and exception to determine if any action is required. Additional information for may be available in the server logs.
  </UserResponse>
</Message>
<Message ID="SRVE8089E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.creating.stats.group" varFormat="Java">
    Error.creating.stats.group=SRVE8089E: Error creating PMI statistics group.
  </MsgText>
  <Explanation>
    Error creating PMI statistics group.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0266E" severity="E" prefix="yes">
  <MsgText pgmKey="error.while.initializing.servlets" varFormat="Java">
    error.while.initializing.servlets=SRVE0266E: Error occured while initializing servlets: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0219I" severity="I" prefix="yes">
  <MsgText pgmKey="No.Error.to.Report" varFormat="Java">
    No.Error.to.Report=SRVE0219I: No Error to Report
  </MsgText>
  <Explanation>
    DefaultErrorReport was invoked but no error was found. This is a system error.
  </Explanation>
  <UserResponse>
    Review application to determine cause of problem.
  </UserResponse>
</Message>
<Message ID="SRVE0298E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.occured.while.creating.wrapper.for.servlet" varFormat="Java">
    exception.occured.while.creating.wrapper.for.servlet=SRVE0298E: Exception occured while creating wrapper for servlet [{0}]: {1}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8066E" severity="E" prefix="yes">
  <MsgText pgmKey="Failed.to.add.WebContainerService" varFormat="Java">
    Failed.to.add.WebContainerService=SRVE8066E: An unexpected exception occurred adding the WebContainerService.
  </MsgText>
  <Explanation>
    An unexpected exception occurred adding the WebContainerService.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8085E" severity="E" prefix="yes">
  <MsgText pgmKey="handleRequest.threw.IOException" varFormat="Java">
    handleRequest.threw.IOException=SRVE8085E: An IOException was thrown from WebContainer&apos;s handleRequest method.
  </MsgText>
  <Explanation>
    An IOException was thrown from WebContainer&apos;s handleRequest method.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM support.
  </UserResponse>
</Message>
<Message ID="SRVE0156E" severity="E" prefix="yes">
  <MsgText pgmKey="failed.to.load.converter.properties" varFormat="Java">
    failed.to.load.converter.properties=SRVE0156E: Failed to load converter.properties file {0}
  </MsgText>
  <Explanation>
    Could not load the specified file. System action is required.
  </Explanation>
  <UserResponse>
    Be sure the specified file existsand is in the correct format according to java.utils.Properties.
  </UserResponse>
</Message>
<Message ID="SRVE8093W" severity="W" prefix="yes">
  <MsgText pgmKey="servlet.classname.is.null" varFormat="Java">
    servlet.classname.is.null=SRVE8093W: The servlet class name is null for the servlet named [{0}] so the request cannot be handled.
  </MsgText>
  <Explanation>
    The servlet class name is null so the request cannot be handled.
  </Explanation>
  <UserResponse>
    Verify a valid servlet class was provided for the servlet.
  </UserResponse>
</Message>
<Message ID="SRVE8098W" severity="W" prefix="yes">
  <MsgText pgmKey="null.url.pattern.for.servlet.mapping" varFormat="Java">
    null.url.pattern.for.servlet.mapping=SRVE8098W: Unable to insert mapping for servlet named [{0}]. URL pattern is null.
  </MsgText>
  <Explanation>
    A servlet mapping is incomplete without a url pattern to map to.
  </Explanation>
  <UserResponse>
    Add a url pattern to the servlet mapping.
  </UserResponse>
</Message>
<Message ID="SRVE8033W" severity="W" prefix="yes">
  <MsgText pgmKey="exception.occurred.while.initializing.ServletContainerInitializers" varFormat="Java">
    exception.occurred.while.initializing.ServletContainerInitializers=SRVE8033W: A problem occurred while initializing the application&apos;s ServletContainerInitializers.
  </MsgText>
  <Explanation>
    A problem occurred while initializing the application&apos;s ServletContainerInitializers.
  </Explanation>
  <UserResponse>
    Verify that the ServletContainerInitializer is configured correctly.
  </UserResponse>
</Message>
<Message ID="SRVE0321E" severity="E" prefix="yes">
  <MsgText pgmKey="init.exception.thrown.by.filter.at.startup" varFormat="Java">
    init.exception.thrown.by.filter.at.startup=SRVE0321E: The [{0}] filter did not load during start up.
  </MsgText>
  <Explanation>
    The filter did not load during startup.
  </Explanation>
  <UserResponse>
    Examine the server logs to determine the root cause of the problem.
  </UserResponse>
</Message>
<Message ID="SRVE8041E" severity="E" prefix="yes">
  <MsgText pgmKey="trying.to.call.dispatch.twice.for.the.same.async.operation" varFormat="Java">
    trying.to.call.dispatch.twice.for.the.same.async.operation=SRVE8041E: trying to call dispatch twice for the same async operation
  </MsgText>
  <Explanation>
    The Servlet specification states you can only call dispatch once per call to startAsync
  </Explanation>
  <UserResponse>
    Remove the additional call to dispatch.
  </UserResponse>
</Message>
<Message ID="SRVE0324W" severity="W" prefix="yes">
  <MsgText pgmKey="ARD.not.enabled.request.on.chains.not.supported" varFormat="Java">
    ARD.not.enabled.request.on.chains.not.supported=SRVE0324W: Asynchronous Request Dispatcher is not enabled. Therefore, the HttpQueueInboundDefault and HttpQueueInboundDefaultSecure chains might not  handle your requests properly .
  </MsgText>
  <Explanation>
    Your requests are on the HttpQueueInboundDefault or HttpQueueInboundDefaultSecure chain, but the Asynchronous Request Dispatcher is not enabled at the server level. Therefore,the HttpQueueInboundDefault and HttpQueueInboundDefaultSecure chains might not handle these requests properly.
  </Explanation>
  <UserResponse>
    Either enable the Asynchronous Request Dispatcher at the server level, or enable either the WCInboundDefault or the WCInboundDefaultSecure chain, and make sure it is running.
  </UserResponse>
</Message>
<Message ID="SRVE0035E" severity="E" prefix="yes">
  <MsgText pgmKey="WebAppSecurityCollaborator" varFormat="Java">
    WebAppSecurityCollaborator=SRVE0035E: WebAppSecurityCollaborator
  </MsgText>
  <Explanation>
    WebAppSecurityCollaborator. This is a system error.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE8034E" severity="E" prefix="yes">
  <MsgText pgmKey="IOException.loading.servlet" varFormat="Java">
    IOException.loading.servlet=SRVE8034E: Servlet [{0}]: {1} could not be loaded due to an IOException.
  </MsgText>
  <Explanation>
    An IOException can occur for any number of reasons related to I/O.
  </Explanation>
  <UserResponse>
    Check if the class has been removed.
  </UserResponse>
</Message>
<Message ID="SRVE0224I" severity="I" prefix="yes">
  <MsgText pgmKey="Target.Servlet" varFormat="Java">
    Target.Servlet=SRVE0224I: Target Servlet:
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0261E" severity="E" prefix="yes">
  <MsgText pgmKey="annotation.helper.not.defined" varFormat="Java">
    annotation.helper.not.defined=SRVE0261E: The annotation helper {0} has not been defined.
  </MsgText>
  <Explanation>
    The specified annotation helper has not been defined. This is a system error.
  </Explanation>
  <UserResponse>
    Check for the definition of the specified annotation helper and add it if necessary.
  </UserResponse>
</Message>
<Message ID="SRVE0068E" severity="E" prefix="yes">
  <MsgText pgmKey="Uncaught.service().exception.thrown.by.servlet" varFormat="Java">
    Uncaught.service().exception.thrown.by.servlet=SRVE0068E: An exception was thrown by one of the service methods of the servlet [{0}] in application [{1}]. Exception created : [{2}]
  </MsgText>
  <Explanation>
    An exception was thrown by one of the service methods of the servlet. This is an application error.
  </Explanation>
  <UserResponse>
    Examine the exception message, the source code of the servlet, and the server logs to determine the root cause of the problem.
  </UserResponse>
</Message>
<Message ID="SRVE8062E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.initializing.security.collaborator" varFormat="Java">
    exception.initializing.security.collaborator=SRVE8062E: An unexpected exception occurred initializing the security collaborator.
  </MsgText>
  <Explanation>
    An unexpected exception occurred initializing the security collaborator.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0269W" severity="W" prefix="yes">
  <MsgText pgmKey="no.jsp.extension.handler.found" varFormat="Java">
    no.jsp.extension.handler.found=SRVE0269W: No Extension Processor found for handling JSPs
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0203E" severity="E" prefix="yes">
  <MsgText pgmKey="Servlet.was.found.but.is.missing.another.required.class" varFormat="Java">
    Servlet.was.found.but.is.missing.another.required.class=SRVE0203E: Servlet [{0}]: {1} was found, but is missing another required class.
  </MsgText>
  <Explanation>
    A required class was not found. This is an application error.
  </Explanation>
  <UserResponse>
    Make sure all required classes are placed in the folders/jars representing the class path
  </UserResponse>
</Message>
<Message ID="SRVE0099E" severity="E" prefix="yes">
  <MsgText pgmKey="Object.Pool.Exception.Class.could.not.be.instantiated.[{0}]" varFormat="Java">
    Object.Pool.Exception.Class.could.not.be.instantiated.[{0}]=SRVE0099E: Object Pool Exception: Class [{0}] could not be instantiated.
  </MsgText>
  <Explanation>
    Could not instantiate a class for use by the object pool. This is a system error.
  </Explanation>
  <UserResponse>
    Be sure the class exists and is visible on the application class path.
  </UserResponse>
</Message>
<Message ID="SRVE8028W" severity="W" prefix="yes">
  <MsgText pgmKey="default.extension.exception.adding.mapping.target" varFormat="Java">
    default.extension.exception.adding.mapping.target=SRVE8028W: An exception occured adding a mapping target for the default extension processor.
  </MsgText>
  <Explanation>
    When two requests are made to the same resource the first time, a race condition can occur in trying to add the mapping to the web application.
  </Explanation>
  <UserResponse>
    This is normally a benign condition that can be ignored. Only report this if there are issues serving any requests to the resources in question.
  </UserResponse>
</Message>
<Message ID="SRVE0202E" severity="E" prefix="yes">
  <MsgText pgmKey="Servlet.found.but.corrupt" varFormat="Java">
    Servlet.found.but.corrupt=SRVE0202E: Servlet [{0}]: {1} was found, but is corrupted:
  </MsgText>
  <Explanation>
    The servlet class was found to be corrupted. This is an application error.
  </Explanation>
  <UserResponse>
    Re-compile the class and try again.
  </UserResponse>
</Message>
<Message ID="SRVE0105E" severity="E" prefix="yes">
  <MsgText pgmKey="Session.releaseSession().threw.an.unexpected.exception" varFormat="Java">
    Session.releaseSession().threw.an.unexpected.exception=SRVE0105E: An exception occurred in Session.releaseSession()
  </MsgText>
  <Explanation>
    Problem releasing a session.
  </Explanation>
  <UserResponse>
    Examine the server logs in order to determine the root cause of the problem. If there are no related messages or they do not help to resolve the problem, contact IBM Support.
  </UserResponse>
</Message>
<Message ID="SRVE8106W" severity="W" prefix="yes">
  <MsgText pgmKey="exception.invoking.async.listener" varFormat="Java">
    exception.invoking.async.listener=SRVE8106W: An exception occurred invoking the async listeners.
  </MsgText>
  <Explanation>
    An exception occurred invoking the async listeners.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE8107W" severity="W" prefix="yes">
  <MsgText pgmKey="trying.to.schedule.timeout.without.cancelling.previous.timeout" varFormat="Java">
    trying.to.schedule.timeout.without.cancelling.previous.timeout=SRVE8107W: The AsyncContext tried to schedule a timeout thread without cancelling the previous timeout.
  </MsgText>
  <Explanation>
    This is an unexpected internal error.
  </Explanation>
  <UserResponse>
    Gather web container trace and contact IBM support.
  </UserResponse>
</Message>
<Message ID="SRVE0169I" severity="I" prefix="yes">
  <MsgText pgmKey="loading.web.module" varFormat="Java">
    loading.web.module=SRVE0169I: Loading Web Module: {0}.
  </MsgText>
  <Explanation>
    Web module is starting and being made available for service.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8051E" severity="E" prefix="yes">
  <MsgText pgmKey="Exception.occured.during.servlet.unload" varFormat="Java">
    Exception.occured.during.servlet.unload=SRVE8051E: An internal server error occurred unloading the servlet.
  </MsgText>
  <Explanation>
    An internal server error occurred unloading the servlet.
  </Explanation>
  <UserResponse>
    See the root cause of the exception.
  </UserResponse>
</Message>
<Message ID="SRVE0305W" severity="W" prefix="yes">
  <MsgText pgmKey="Object.Pool.Disabled" varFormat="Java">
    Object.Pool.Disabled=SRVE0305W: ObjectPoolService is unavailable. SRTConnectionContext pooling disabled.
  </MsgText>
  <Explanation>
    The object pool service improves the performance of the web container, but it has been disabled. This is a system error.
  </Explanation>
  <UserResponse>
    It is recommended to enable the object pool service.
  </UserResponse>
</Message>
<Message ID="SRVE0258W" severity="W" prefix="yes">
  <MsgText pgmKey="property.not.applicable" varFormat="Java">
    property.not.applicable=SRVE0258W: The {0} attribute under the transport no longer applies.
  </MsgText>
  <Explanation>
    System action is required.
  </Explanation>
  <UserResponse>
    Configure this property under the Logging Service (see information center for more details on HTTP Access Logger).
  </UserResponse>
</Message>
<Message ID="SRVE8083E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.occurred.while.registering.WebModule.MBean" varFormat="Java">
    Error.occurred.while.registering.WebModule.MBean=SRVE8083E: An unexpected internal server error occurred while registering web module MBean.
  </MsgText>
  <Explanation>
    An unexpected internal server error occurred while registering web module MBean.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0240I" severity="I" prefix="yes">
  <MsgText pgmKey="ExtensionFactory.[{0}].associated.with.patterns.[{1}]" varFormat="Java">
    ExtensionFactory.[{0}].associated.with.patterns.[{1}]=SRVE0240I: Extension Factory [{0}] has been associated with patterns [{1}].
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0232E" severity="E" prefix="yes">
  <MsgText pgmKey="Engine.Exception.[{0}]" varFormat="Java">
    Engine.Exception.[{0}]=SRVE0232E: Internal Server Error. &lt;br&gt; Exception Message: [{0}]
  </MsgText>
  <Explanation>
    An unexpected exception occurred and details were provided on the resulting error page. This is a system error.
  </Explanation>
  <UserResponse>
    Check the System.out and System.err logs for more information on the exception generated.
  </UserResponse>
</Message>
<Message ID="SRVE0273E" severity="E" prefix="yes">
  <MsgText pgmKey="error.while.initializing.jsp.as.servlet" varFormat="Java">
    error.while.initializing.jsp.as.servlet=SRVE0273E: Error while initializing JSP as servlet [{0}] in application [{1}]: {1}
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0314E" severity="E" prefix="yes">
  <MsgText pgmKey="failed.to.remove.webmodule" varFormat="Java">
    failed.to.remove.webmodule=SRVE0314E: Failed to remove web module {0}: {1}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0326E" severity="E" prefix="yes">
  <MsgText pgmKey="Exceeding.maximum.hash.collisions" varFormat="Java">
    Exceeding.maximum.hash.collisions=SRVE0326E: The maximum number of parameter key hashcode collisions allowed per request {0} has been exceeded.
  </MsgText>
  <Explanation>
    The number of parameter key hash code collisions exceeds the maximum number of parameter key hash code collisions allowed per inbound request. The parameter keys that generate duplicate hashcodes might have been added to the request maliciously, thereby causing a large number of parameter key hash code collisions.
  </Explanation>
  <UserResponse>
    Ensure that all of the parameters in the inbound request are valid.
  </UserResponse>
</Message>
<Message ID="SRVE0323I" severity="I" prefix="yes">
  <MsgText pgmKey="ARD.not.enabled.these.chains.not.supported" varFormat="Java">
    ARD.not.enabled.these.chains.not.supported=SRVE0323I: The Asynchronous Request Dispatcher is not enabled. Requests sent through either the HttpQueueInboundDefault or the HttpQueueInboundDefaultSecure chain might not be properly handled.
  </MsgText>
  <Explanation>
    The requests through either the HttpQueueInboundDefault or the HttpQueueInboundDefaultSecure chain might not be properly handled if the Asynchronous Request Dispatcher is not enabled at the server level.
  </Explanation>
  <UserResponse>
    If Asynchronous Request Dispatcher is not enabled at the server level, make sure either the WCInboundDefault or the WCInboundDefaultSecure chain is enabled and running. If neither of these chains is running, you must enable the Asynchronous Request Dispatcher if it is not already enabled because the server will send the requests through either the HttpQueueInboundDefault or the HttpQueueInboundDefaultSecure chain.
  </UserResponse>
</Message>
<Message ID="SRVE8099W" severity="W" prefix="yes">
  <MsgText pgmKey="stub.restart.web.application" varFormat="Java">
    stub.restart.web.application=SRVE8099W: The method restartWebApplication no longer does anything. Use the ApplicationManager MBean to start and restart an application.
  </MsgText>
  <Explanation>
    The method restartWebApplication no longer does anything. Use the ApplicationManager MBean to start and restart an application.
  </Explanation>
  <UserResponse>
    The method restartWebApplication no longer does anything. Use the ApplicationManager MBean to start and restart an application.
  </UserResponse>
</Message>
<Message ID="SRVE0309E" severity="E" prefix="yes">
  <MsgText pgmKey="servlet.on.blocked.list.{0}" varFormat="Java">
    servlet.on.blocked.list.{0}=SRVE0309E: Servlet on the blocked list: {0}
  </MsgText>
  <Explanation>
    The requested servlet is on the block list provided by the custom property com.ibm.ws.webcontainer.donotservebyclassname. This is an application error.
  </Explanation>
  <UserResponse>
    If this is not the desired behavior, update the property com.ibm.ws.webcontainer.donotservebyclassname.
  </UserResponse>
</Message>
<Message ID="SRVE0190E" severity="E" prefix="yes">
  <MsgText pgmKey="File.not.found" varFormat="Java">
    File.not.found=SRVE0190E: File not found: {0}
  </MsgText>
  <Explanation>
    The mentioned file was not found. This is an application error.
  </Explanation>
  <UserResponse>
    Ensure that the mentioned file is in place.
  </UserResponse>
</Message>
<Message ID="SRVE8076E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.AsyncRequestDispatcherConfigImpl.object" varFormat="Java">
    Null.AsyncRequestDispatcherConfigImpl.object=SRVE8076E: Null AsyncRequestDispatcherConfigImpl object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE8081E" severity="E" prefix="yes">
  <MsgText pgmKey="Error.occurred.while.adding.WebAppCollaborator" varFormat="Java">
    Error.occurred.while.adding.WebAppCollaborator=SRVE8081E: An unexpected internal server error occurred while adding a web application collaborator.
  </MsgText>
  <Explanation>
    An unexpected internal server error occurred while adding a web application collaborator.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0257W" severity="W" prefix="yes">
  <MsgText pgmKey="property.has.changed" varFormat="Java">
    property.has.changed=SRVE0257W: The semantics for the {0} property on the transport have changed.
  </MsgText>
  <Explanation>
    A thread is no longer tied to a single connection. System action is required.
  </Explanation>
  <UserResponse>
    Refer to the information center for more details.
  </UserResponse>
</Message>
<Message ID="SRVE0230E" severity="E" prefix="yes">
  <MsgText pgmKey="class.compiled.using.proper.case" varFormat="Java">
    class.compiled.using.proper.case=SRVE0230E: Check that the class was compiled using the proper case (as defined in the class definition).
  </MsgText>
  <Explanation>
    This is an application error.
  </Explanation>
  <UserResponse>
    Check that the class was compiled using the proper case (as defined in the class definition).
  </UserResponse>
</Message>
<Message ID="SRVE8064E" severity="E" prefix="yes">
  <MsgText pgmKey="Could.not.create.LogoutProcessor" varFormat="Java">
    Could.not.create.LogoutProcessor=SRVE8064E: An unexpected exception occurred initializing the logout processor.
  </MsgText>
  <Explanation>
    An unexpected exception occurred initializing the logout processor.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0218E" severity="E" prefix="yes">
  <MsgText pgmKey="Forbidden.Web.Security.Exception" varFormat="Java">
    Forbidden.Web.Security.Exception=SRVE0218E: Forbidden: Web Security Exception
  </MsgText>
  <Explanation>
    The request tried to access a forbidden resource.
  </Explanation>
  <UserResponse>
    Make sure the requesting entity has the required privileges.
  </UserResponse>
</Message>
<Message ID="SRVE0244I" severity="I" prefix="yes">
  <MsgText pgmKey="reaper.unloading.servlet.[{0}]" varFormat="Java">
    reaper.unloading.servlet.[{0}]=SRVE0244I: Reaper thread unloading servlet: [{0}].
  </MsgText>
  <Explanation>
    The reaper thread removes servlets that have been inactive for longer than the reaper inactive limit.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8030E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.occured.while.adding.servlet" varFormat="Java">
    exception.occured.while.adding.servlet=SRVE8030E: A ServletException occurred adding a servlet dynamically.
  </MsgText>
  <Explanation>
    An unexpected ServletException occurred adding a servlet dynamically. This can occur, for example, if the MBean names of two servlets collide.
  </Explanation>
  <UserResponse>
    Review the logs and contact support.
  </UserResponse>
</Message>
<Message ID="SRVE8007E" severity="E" prefix="yes">
  <MsgText pgmKey="add.filter.mapping.to.null.servlet.names" varFormat="Java">
    add.filter.mapping.to.null.servlet.names=SRVE8007E: Attempted to add a filter mapping with the variable argument servlet name parameter set to null.
  </MsgText>
  <Explanation>
    The variable argument servlet name parameter passed to FilterRegistration.addMappingForServletNames must be non-null and non-empty.
  </Explanation>
  <UserResponse>
    Modify application code according to error explanation.
  </UserResponse>
</Message>
<Message ID="SRVE8070E" severity="E" prefix="yes">
  <MsgText pgmKey="failed.to.initialize.webcontainer.required.to.start.chains" varFormat="Java">
    failed.to.initialize.webcontainer.required.to.start.chains=SRVE8070E: An unexpected error occurred starting the web container channel chains.
  </MsgText>
  <Explanation>
    An unexpected error occurred starting the web container channel chains.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0196E" severity="E" prefix="yes">
  <MsgText pgmKey="Missing.required.initialization.parameter" varFormat="Java">
    Missing.required.initialization.parameter=SRVE0196E: Missing required initialization parameter: {0}
  </MsgText>
  <Explanation>
    The parameter with the mentioned name has no value. This is a required parameter. This is an application error.
  </Explanation>
  <UserResponse>
    Supply a value to the mentioned parameter.
  </UserResponse>
</Message>
<Message ID="SRVE0200E" severity="E" prefix="yes">
  <MsgText pgmKey="Servlet.Could.not.find.required.servlet.class" varFormat="Java">
    Servlet.Could.not.find.required.servlet.class=SRVE0200E: Servlet [{0}]: Could not find required class - {1}
  </MsgText>
  <Explanation>
    Servlet could not find a required class needed to service the request. This is an application error.
  </Explanation>
  <UserResponse>
    Verify the class exists within the application.
  </UserResponse>
</Message>
<Message ID="SRVE8042E" severity="E" prefix="yes">
  <MsgText pgmKey="reference.context.not.set" varFormat="Java">
    reference.context.not.set=SRVE8042E: An internal error caused the reference context that enables injection to not be initialized properly.
  </MsgText>
  <Explanation>
    An internal error caused the reference context that enables injection to not be initialized properly.
  </Explanation>
  <UserResponse>
    Check for errors earlier in the logs that may have caused initialization to fail.
  </UserResponse>
</Message>
<Message ID="SRVE0235E" severity="E" prefix="yes">
  <MsgText pgmKey="[{0}].reported.an.error" varFormat="Java">
    [{0}].reported.an.error=SRVE0235E: [{0}] reported an error
  </MsgText>
  <Explanation>
    See reported error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0290E" severity="E" prefix="yes">
  <MsgText pgmKey="unable.to.use.specified.temp.directory" varFormat="Java">
    unable.to.use.specified.temp.directory=SRVE0290E: Unable to use specified temp directory: {0} read:{1} write:{2}
  </MsgText>
  <Explanation>
    System action is required.
  </Explanation>
  <UserResponse>
    Check the status of the directory, including existence, access privileges and available space.
  </UserResponse>
</Message>
<Message ID="SRVE0161I" severity="I" prefix="yes">
  <MsgText pgmKey="web.container.copyright" varFormat="Java">
    web.container.copyright=SRVE0161I: IBM WebSphere Application Server - Web Container.  Copyright IBM Corp. 1998-2012
  </MsgText>
  <Explanation>
    Application server identifier.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0058E" severity="E" prefix="yes">
  <MsgText pgmKey="Uncaught.destroy().exception.thrown.by.servlet" varFormat="Java">
    Uncaught.destroy().exception.thrown.by.servlet=SRVE0058E: Did not realize destroy() exception created by servlet {0} in application {1}: {2}
  </MsgText>
  <Explanation>
    The servlet destroy() method threw an exception. This is an application error.
  </Explanation>
  <UserResponse>
    Examine the exception message, the source code of the servlet, and the server logs to determine the root cause of the problem.
  </UserResponse>
</Message>
<Message ID="SRVE0186E" severity="E" prefix="yes">
  <MsgText pgmKey="Cannot.set.buffer.size.after.data" varFormat="Java">
    Cannot.set.buffer.size.after.data=SRVE0186E: Can&apos;t set buffer size after data has been written to stream
  </MsgText>
  <Explanation>
    Some data has already been written to the stream, and hence the buffer size can no longer be controlled. This is an application error.
  </Explanation>
  <UserResponse>
    Either set the buffer size before writing data or reset the buffer before setting the size.
  </UserResponse>
</Message>
<Message ID="SRVE0205E" severity="E" prefix="yes">
  <MsgText pgmKey="host.on.port.has.not.been.defined" varFormat="Java">
    host.on.port.has.not.been.defined=SRVE0205E: The host {0} on port {1} has not been defined.
  </MsgText>
  <Explanation>
    Unable to locate Virtual Host defined to handle this request URI. System action is required.
  </Explanation>
  <UserResponse>
    Check the virtual host configuration in the virtualhosts.xml file, or through the administrative console.
  </UserResponse>
</Message>
<Message ID="SRVE8092W" severity="W" prefix="yes">
  <MsgText pgmKey="exception.invoking.asnyc.error.mechanism" varFormat="Java">
    exception.invoking.asnyc.error.mechanism=SRVE8092W: An exception occurred invoking the async error mechanism.
  </MsgText>
  <Explanation>
    An exception occurred invoking the async error mechanism.
  </Explanation>
  <UserResponse>
    See root cause.
  </UserResponse>
</Message>
<Message ID="SRVE0061E" severity="E" prefix="yes">
  <MsgText pgmKey="Illegal.Argument:.Invalid.Directory.Specified:.{0}" varFormat="Java">
    Illegal.Argument:.Invalid.Directory.Specified:.{0}=SRVE0061E: Illegal Argument Exception: Invalid directory specified: {0}
  </MsgText>
  <Explanation>
    The specified directory is not valid.
  </Explanation>
  <UserResponse>
    Check directory specification for errors.
  </UserResponse>
</Message>
<Message ID="SRVE0284E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.caught.in.notifyServletContextCreated" varFormat="Java">
    exception.caught.in.notifyServletContextCreated=SRVE0284E: Exception caught in notifyServletContextCreated: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE8043E" severity="E" prefix="yes">
  <MsgText pgmKey="ioexception.searching.jar.for.resource" varFormat="Java">
    ioexception.searching.jar.for.resource=SRVE8043E: An IOException occured searching jarFile [{1}] for fileName [{2}] {0}
  </MsgText>
  <Explanation>
    IOExceptions can occur when looking at jar files if the file is changed or closed during traversal.
  </Explanation>
  <UserResponse>
    Verify the jar file is valid and is not being updated during traversal.
  </UserResponse>
</Message>
<Message ID="SRVE0155E" severity="E" prefix="yes">
  <MsgText pgmKey="failed.to.load.encoding.properties" varFormat="Java">
    failed.to.load.encoding.properties=SRVE0155E: Failed to load encoding.properties file {0}
  </MsgText>
  <Explanation>
    Could not load the specified file. System action is required.
  </Explanation>
  <UserResponse>
    Be sure the specified file exists and is in the correct format according to java.utils.Properties.
  </UserResponse>
</Message>
<Message ID="SRVE0248I" severity="I" prefix="yes">
  <MsgText pgmKey="waiting.to.destroy.filter.[{0}]" varFormat="Java">
    waiting.to.destroy.filter.[{0}]=SRVE0248I: Requests are currently being processed. Waiting up to 60 seconds before forcing filter destroy.
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0204E" severity="E" prefix="yes">
  <MsgText pgmKey="host.has.not.been.defined" varFormat="Java">
    host.has.not.been.defined=SRVE0204E: The host {0} has not been defined
  </MsgText>
  <Explanation>
    The virtual host was not found. System action is required.
  </Explanation>
  <UserResponse>
    Check the virtual host configuration in the virtualhosts.xml file, or through the administrative console.
  </UserResponse>
</Message>
<Message ID="SRVE8110E" severity="E" prefix="yes">
  <MsgText pgmKey="exception.occured.while.processing.ServletContainerInitializer.initializeExtensionPointSCIs" varFormat="Java">
    exception.occured.while.processing.ServletContainerInitializer.initializeExtensionPointSCIs=SRVE8110E: Could not initialize ServletContainerInitializer: Classname: [{0}].
  </MsgText>
  <Explanation>
    The ServletContainerInitializer specified by the Extension Point could not be initialized.
  </Explanation>
  <UserResponse>
    Check the class specified in the Extension Point.
  </UserResponse>
</Message>
<Message ID="SRVE0281E" severity="E" prefix="yes">
  <MsgText pgmKey="request.processor.already.present.for.mapping" varFormat="Java">
    request.processor.already.present.for.mapping=SRVE0281E: Request Processor already present for mapping: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0265E" severity="E" prefix="yes">
  <MsgText pgmKey="error.notifying.listeners.of.WebApp.start" varFormat="Java">
    error.notifying.listeners.of.WebApp.start=SRVE0265E: Error occured while notifying listeners of web application start: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    Review the logs.
  </UserResponse>
</Message>
<Message ID="SRVE0260E" severity="E" prefix="yes">
  <MsgText pgmKey="cannot.use.error.page" varFormat="Java">
    cannot.use.error.page=SRVE0260E: The server cannot use the error page specified for your application to handle the Original Exception printed below.
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    See the Error Page Exception for a description of the problem with the specified error page.
  </UserResponse>
</Message>
<Message ID="SRVE0223I" severity="I" prefix="yes">
  <MsgText pgmKey="StackTrace" varFormat="Java">
    StackTrace=SRVE0223I: StackTrace:
  </MsgText>
  <Explanation>
    none.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0211E" severity="E" prefix="yes">
  <MsgText pgmKey="class.{0}.could.not.be.instantiated" varFormat="Java">
    class.{0}.could.not.be.instantiated=SRVE0211E: The class {0} could not be instantiated
  </MsgText>
  <Explanation>
    Internal exception.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="SRVE0021I" severity="I" prefix="yes">
  <MsgText pgmKey="Servlet.unloaded:.{0}" varFormat="Java">
    Servlet.unloaded:.{0}=SRVE0021I: Servlet unloaded: {0}
  </MsgText>
  <Explanation>
    The specified servlet has been unloaded after the destroy method has been called.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8079E" severity="E" prefix="yes">
  <MsgText pgmKey="Null.filter.config.object" varFormat="Java">
    Null.filter.config.object=SRVE8079E: Null filter config object.
  </MsgText>
  <Explanation>
    An unexpected configuration exceptoin occurred.
  </Explanation>
  <UserResponse>
    Gather server logs and contact IBM service.
  </UserResponse>
</Message>
<Message ID="SRVE0306W" severity="W" prefix="yes">
  <MsgText pgmKey="ARD.Not.Enabled" varFormat="Java">
    ARD.Not.Enabled=SRVE0306W: ARD is not enabled so an asynchronous include or insertFragment call will be synchronous.
  </MsgText>
  <Explanation>
    ARD is not enabled correctly. System action is required.
  </Explanation>
  <UserResponse>
    Make sure ARD is enabled in the Web Container settings and a dispatch type of CLIENT_SIDE or SERVER_SIDE is specified in the application settings.
  </UserResponse>
</Message>
<Message ID="SRVE0325E" severity="E" prefix="yes">
  <MsgText pgmKey="Exceeding.maximum.parameters" varFormat="Java">
    Exceeding.maximum.parameters=SRVE0325E: Exceeding maximum parameters allowed per request {0} ,current {1} , cannot add more.
  </MsgText>
  <Explanation>
    The number of parameters contained in the inbound request exceeds the maximum number of parameters that can be included in a inbound request.
  </Explanation>
  <UserResponse>
    Ensure that all of the parameters in the inbound request are valid, and that the total number parameters does not exceed the maximum allowed per request.
  </UserResponse>
</Message>
<Message ID="SRVE8044E" severity="E" prefix="yes">
  <MsgText pgmKey="programmatic.sessions.already.been.initialized" varFormat="Java">
    programmatic.sessions.already.been.initialized=SRVE8044E: The context has already been initialized.  No updates are allowed to the session configuration.
  </MsgText>
  <Explanation>
    The context has already been initialized.  No updates are allowed to the session configuration.
  </Explanation>
  <UserResponse>
    You can only modify the session configuration before the application is initialized.
  </UserResponse>
</Message>
<Message ID="SRVE0251W" severity="W" prefix="yes">
  <MsgText pgmKey="threadpool.not.used" varFormat="Java">
    threadpool.not.used=SRVE0251W: The thread pool configured under the web container is not being used.
  </MsgText>
  <Explanation>
    There exists a thread pool configuration under the web container. Any changes made to this configuration item will not result in changes in the system.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE8039E" severity="E" prefix="yes">
  <MsgText pgmKey="not.called.from.within.the.context.of.a.dispatch.for.this.request" varFormat="Java">
    not.called.from.within.the.context.of.a.dispatch.for.this.request=SRVE8039E: The method startAsync was not called from within the context of a dispatch for this request
  </MsgText>
  <Explanation>
    The method startAsync must be called from within the context of a container dispatch be it the original request or a subsequent async dispatch.
  </Explanation>
  <UserResponse>
    Verify there are no code logic or timing issues causing this illegal behavior.
  </UserResponse>
</Message>
<Message ID="SRVE8112W" severity="W" prefix="yes">
  <MsgText pgmKey="programmatic.session.cookie.retrieve.cell.xml.failure" varFormat="Java">
    programmatic.session.cookie.retrieve.cell.xml.failure=SRVE8112W: There was a problem retrieving the restricted cookie patterns.  No restrictions have been placed on the programmatic session configuration.
  </MsgText>
  <Explanation>
    There was a problem retrieving the restricted cookie patterns from the configuration.
  </Explanation>
  <UserResponse>
    Verify that the cell.xml exists and is readable.
  </UserResponse>
</Message>
<Message ID="SRVE8050E" severity="E" prefix="yes">
  <MsgText pgmKey="Place.servlet.class.on.classpath.of.the.application.server" varFormat="Java">
    Place.servlet.class.on.classpath.of.the.application.server=SRVE8050E: Place servlet class on classpath of the application server {0}, {1}: {2}.
  </MsgText>
  <Explanation>
    Classpath errors occurred when serving the servlet.
  </Explanation>
  <UserResponse>
    Place servlet class on classpath of the application server.
  </UserResponse>
</Message>
<Message ID="SRVE0097I" severity="I" prefix="yes">
  <MsgText pgmKey="Servlet.unload.initiated:.{0}" varFormat="Java">
    Servlet.unload.initiated:.{0}=SRVE0097I: Servlet unload initiated: {0}
  </MsgText>
  <Explanation>
    The specified servlet is being unloaded from service.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0289E" severity="E" prefix="yes">
  <MsgText pgmKey="failed.to.create.temp.directory" varFormat="Java">
    failed.to.create.temp.directory=SRVE0289E: Failed to create temp directory: {0}
  </MsgText>
  <Explanation>
    This is a system error.
  </Explanation>
  <UserResponse>
    none.
  </UserResponse>
</Message>
<Message ID="SRVE0212E" severity="E" prefix="yes">
  <MsgText pgmKey="class.{0}.not.accessible" varFormat="Java">
    class.{0}.not.accessible=SRVE0212E: class {0} not accessible
  </MsgText>
  <Explanation>
    Internal exception.
  </Explanation>
  <UserResponse>
    If the problem persists, additional information might be available if you search for the message ID on the following Web sites: WebSphere Application Server Support page: http://www.ibm.com/software/webservers/appserv/was/support/ WebSphere Application Server for z/OS Support page: http://www.ibm.com/software/webservers/appserv/zos_os390/support/ .
  </UserResponse>
</Message>
<Message ID="SRVE0234I" severity="I" prefix="yes">
  <MsgText pgmKey="Application.classpath" varFormat="Java">
    Application.classpath=SRVE0234I: Application class path=[{0}]
  </MsgText>
  <Explanation>
    none
  </Explanation>
  <UserResponse>
    none
  </UserResponse>
</Message>
<Message ID="SRVE8031W" severity="W" prefix="yes">
  <MsgText pgmKey="exception.occurred.while.initializing.ServletContainerInitializers.class.lookup" varFormat="Java">
    exception.occurred.while.initializing.ServletContainerInitializers.class.lookup=SRVE8031W: A problem finding class, {0}, during the scan for ServletContainerInitializer HandlesTypes for {1}.
  </MsgText>
  <Explanation>
    The class was not found in the class loader when processing the ServletContainerInitializer HandlesTypes annotation.
  </Explanation>
  <UserResponse>
    Make sure the class exists within the web module&apos;s class loader.
  </UserResponse>
</Message>
<!-- END MESSAGES -->
</TMSSource>
