[3/5/18 12:34:53:863 UTC]     FFDC Exception:org.apache.soap.SOAPException SourceId:com.ibm.ws.management.connector.soap.SOAPUtils.extractSoapCall ProbeId:157
[SOAPException: faultCode=SOAP-ENV:ServerException; msg=Unable to authenticate incoming request]
	at com.ibm.ws.management.connector.soap.SOAPUtils.authenticateUser(SOAPUtils.java:628)
	at com.ibm.ws.management.connector.soap.SOAPUtils.retrieveSubject(SOAPUtils.java:581)
	at com.ibm.ws.management.connector.soap.SOAPUtils.authSOAPRequest(SOAPUtils.java:511)
	at com.ibm.ws.management.connector.soap.SOAPUtils.extractSoapCall(SOAPUtils.java:154)
	at com.ibm.ws.management.connector.soap.SOAPConnector.service(SOAPConnector.java:169)
	at com.ibm.ws.management.connector.soap.SOAPConnection.handleRequest(SOAPConnection.java:65)
	at com.ibm.ws.http.HttpConnection.readAndHandleRequest(HttpConnection.java:733)
	at com.ibm.ws.http.HttpConnection.run(HttpConnection.java:522)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)

==> Performing default dump from com.ibm.ws.management.dm.ConnectorDM :Mon Mar 05 12:34:53 UTC 2018
IntrospectDepth set from:3 to: 5
Dump of callerThis:null
IntrospectDepth reset to:3
+Data for directive [defaultconnector] obtained.:
==> Dump complete for com.ibm.ws.management.dm.ConnectorDM :Mon Mar 05 12:34:53 UTC 2018
